#!/usr/bin/env python3
"""Debug card 579 bytecode generation to identify missing comparison mode."""

import json
import sys
from engine.models.ability import Ability
from engine.models.generated_enums import ConditionType, TriggerType, EffectType, TargetType, AbilityCostType
from engine.models.ability import Condition, Effect

def test_card_579_bytecode():
    """Test the bytecode generation for card 579's SYNC_COST condition."""
    
    # Create the condition exactly as it should be for card 579
    sync_cost_condition = Condition(
        type=ConditionType.SYNC_COST,
        params={
            "PLAYER_CENTER_FILTER": "GROUP_ID=3",
            "raw_cond": "PLAYER_CENTER_COST_GT_OPPONENT_CENTER_COST",
            "area": "CENTER",
            "comparison": "GT",
            "val": "0"
        },
        is_negated=False
    )
    
    # Create the effect (BOOST_SCORE)
    boost_effect = Effect(
        effect_type=EffectType.BOOST_SCORE,
        value=1,
        target=TargetType.SELF,
        params={}
    )
    
    # Create the ability
    ability = Ability(
        raw_text="TRIGGER: ON_LIVE_START\nCONDITION: PLAYER_CENTER_COST_GT_OPPONENT_CENTER_COST {PLAYER_CENTER_FILTER=\"GROUP_ID=3\"}\nEFFECT: BOOST_SCORE(1) -> SELF",
        trigger=TriggerType.ON_LIVE_START,
        effects=[boost_effect],
        conditions=[sync_cost_condition],
        card_no="PL!SP-bp4-024-L"
    )
    
    print("=" * 60)
    print("DEBUG: Card 579 Bytecode Generation")
    print("=" * 60)
    print(f"Condition type: {sync_cost_condition.type.name}")
    print(f"Condition params: {json.dumps(sync_cost_condition.params, ensure_ascii=False, indent=2)}")
    print()
    
    # Compile the bytecode
    bytecode = ability.compile()
    print(f"Generated bytecode: {bytecode}")
    print()
    
    # Analyze the bytecode
    print("Bytecode Analysis (5-byte chunks):")
    for i in range(0, len(bytecode), 5):
        if i + 4 < len(bytecode):
            op = bytecode[i]
            v = bytecode[i + 1]
            a_low = bytecode[i + 2]
            a_high = bytecode[i + 3]
            raw_s = bytecode[i + 4]
            
            # Convert raw_s (slot) to binary for analysis  
            slot_binary = f"{raw_s:032b}"
            # Extract area_idx at bits 29-31
            area_idx = (raw_s >> 29) & 0x7
            # Extract comp_val at bits 4-7
            comp_val = (raw_s >> 4) & 0x0F
            
            print(f"Chunk {i//5}:")
            print(f"  op={op}, v={v}, a_low={a_low}, a_high={a_high}")
            print(f"  raw_s=0x{raw_s:08x} ({raw_s}) = {slot_binary}")
            print(f"    bits 4-7 (comp_val): {comp_val}")
            print(f"    bits 29-31 (area_idx): {area_idx}")
    
    print()
    print("Expected values for SYNC_COST with CENTER and GT:")
    print("  comp_val should be: 1 (for GT)")
    print("  area_idx should be: 2 (for CENTER)")
    print("  packed_slot should have both bits set correctly")
    
    # Now check what the actual compiled JSON shows
    print("\n" + "=" * 60)
    print("Comparing with compiled JSON:")
    print("=" * 60)
    try:
        with open("data/cards_compiled.json", "r", encoding="utf-8") as f:
            compiled_data = json.load(f)
        
        if "579" in compiled_data.get("live_db", {}):
            card_data = compiled_data["live_db"]["579"]
            if card_data.get("abilities"):
                first_ab = card_data["abilities"][0]
                json_bytecode = first_ab.get("bytecode", [])
                print(f"JSON bytecode: {json_bytecode}")
                print(f"Our compiled bytecode: {bytecode}")
                print(f"Match: {json_bytecode == bytecode}")
    except Exception as e:
        print(f"Error reading compiled JSON: {e}")

if __name__ == "__main__":
    test_card_579_bytecode()
