import json
import re

translations_map = {
    # [2] PL!HS-bp1-003-R＋
    "{{jyouji.png|常時}}自分のステージのエリアすべてに『蓮ノ空』のメンバーが登場しており、かつ名前が異なる場合、「{{jyouji.png|常時}}ライブの合計スコアを＋１する。」を得る。\n{{kidou.png|起動}}{{turn1.png|ターン1回}}{{icon_energy.png|E}}：自分の控え室から4コスト以下の『蓮ノ空』のメンバーカードを1枚手札に加える。": "[Continuous] If you have 'Hasunosora' members in all areas of your stage and they have different names, this member gets \"[Continuous] Live Score +1\".\n[Activate] [Turn 1] (E): Add 1 'Hasunosora' Member card with Cost 4 or less from your waiting room to your hand.",
    # [2] PL!HS-bp1-004-R＋
    "{{kidou.png|起動}}{{turn1.png|ターン1回}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}：自分の控え室から『蓮ノ空』のライブカードを1枚手札に加える。\n{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}支払ってもよい：ライブ終了時まで、自分のライブ中のカード1枚につき、{{icon_blade.png|ブレード}}を得る。": "[Activate] [Turn 1] (E)(E)(E): Add 1 'Hasunosora' Live card from your waiting room to your hand.\n[Live Start] You may pay (E): This member gets +1 Blade for each of your Live cards in progress until the end of the live phase.",
    # [2] PL!HS-bp1-006-R＋
    "{{toujyou.png|登場}}カードを2枚引き、手札を1枚控え室に置く。\n{{live_start.png|ライブ開始時}}手札を1枚控え室に置いてもよい：自分のステージにほかのメンバーがいる場合、好きなハートの色を1つ指定する。ライブ終了時まで、そのハートを1つ得る。": "[On Play] Draw 2 cards, then put 1 card from your hand into the waiting room.\n[Live Start] You may put 1 card from your hand into the waiting room: If you have another member on your stage, choose 1 Heart color. This member gets 1 Heart of the chosen color until the end of the live phase.",
    # [2] PL!SP-pb1-004-R
    "{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：自分のエネルギーデッキから、エネルギーカードを1枚ウェイト状態で置く。\n{{live_success.png|ライブ成功時}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：カードを1枚引く。": "[Live Start] You may pay (E)(E): Place 1 Energy card from your Energy Deck into your Energy Area in Waiting state.\n[Live Success] You may pay (E)(E)(E): Draw 1 card.",
    # [2] PL!S-bp2-007-R＋
    "{{jidou.png|自動}}［ターン1回］エールにより公開された自分のカードの中にライブカードが1枚以上あるとき、自分の手札が7枚以下の場合、カードを1枚引く。\n{{live_start.png|ライブ開始時}}手札のライブカードを1枚公開し、デッキの一番下に置いてもよい：自分のデッキの上からカードを2枚見る。その中から好きな枚数を好きな順番でデッキの上に置き、残りを控え室に置く。": "[Auto] [Turn 1] When you reveal 1 or more Live cards via Yell, if you have 7 or fewer cards in hand, draw 1 card.\n[Live Start] You may reveal 1 Live card from your hand and put it on the bottom of your deck: Look at the top 2 cards of your deck. Put any number of them back on top of the deck in any order, and put the rest into the waiting room.",
    # [2] PL!S-bp2-008-R＋
    "{{toujyou.png|登場}}自分の控え室からライブカードを1枚までデッキの一番下に置く。\n{{jyouji.png|常時}}自分のステージのエリアすべてに『Aqours』のメンバーが登場しており、かつ名前が異なる場合、「{{live_success.png|ライブ成功時}}エールにより公開された自分のカードの中にライブカードが1枚以上ある場合、ライブの合計スコアを＋１する。ライブカードが3枚以上ある場合、代わりに合計スコアを＋２する。」を得る。": "[On Play] Put up to 1 Live card from your waiting room on the bottom of your deck.\n[Continuous] If you have 'Aqours' members in all areas of your stage and they have different names, this member gets \"[Live Success] If 1 or more Live cards are revealed by your Yell, Live Score +1. If 3 or more Live cards are revealed, Live Score +2 instead.\"",
    # [2] PL!SP-bp2-006-R＋
    "{{toujyou.png|登場}}バトンタッチして登場した場合、このバトンタッチで控え室に置かれた『Liella!』のメンバーカードを1枚手札に加える。\n{{kidou.png|起動}}{{turn1.png|ターン1回}}手札のコスト4以下の『Liella!』のメンバーカードを1枚控え室に置く：これにより控え室に置いたメンバーカードの{{toujyou.png|登場}}能力1つを発動させる。\n({{toujyou.png|登場}}能力がコストを持つ場合、支払って発動させる。)": "[On Play] If entered via Baton Touch, add 1 'Liella!' Member card put into the waiting room by this Baton Touch to your hand.\n[Activate] [Turn 1] Put 1 'Liella!' Member card with Cost 4 or less from your hand into the waiting room: Activate 1 [On Play] ability of the member card put into the waiting room by this effect.\n(If the [On Play] ability has a cost, you must pay it to activate.)",
    # [2] PL!SP-bp2-009-R＋
    "{{live_start.png|ライブ開始時}}ライブ終了時まで、自分の手札2枚につき、{{icon_blade.png|ブレード}}を得る。\n{{live_success.png|ライブ成功時}}カードを2枚引き、手札を1枚控え室に置く。": "[Live Start] This member gets +1 Blade for every 2 cards in your hand until the end of the live phase.\n[Live Success] Draw 2 cards, then put 1 card from your hand into the waiting room.",
    # [2] PL!SP-bp2-010-R＋
    "{{jyouji.png|常時}}相手のライブカード置き場にあるすべてのライブカードは、成功させるための必要ハートが{{heart_00.png|heart0}}多くなる。\n{{live_start.png|ライブ開始時}}自分のステージにこのメンバー以外のメンバーが1人以上いる場合、ライブ終了時まで、エールによって公開される自分のカードの枚数が8枚減る。": "[Continuous] All Live cards in your opponent's Live Area require +1 [Heart 00] to succeed.\n[Live Start] If you have 1 or more other members on your stage, reduce the number of cards revealed by your Yell by 8 until the end of the live phase.",
    # [2] PL!HS-bp2-002-R＋
    "{{toujyou.png|登場}}自分の控え室からコスト2以下のメンバーカードを2枚まで手札に加える。\n{{jyouji.png|常時}}自分のステージに、このメンバーよりコストの大きいメンバーがいる場合、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[On Play] Add up to 2 Member cards with Cost 2 or less from your waiting room to your hand.\n[Continuous] If you have a member with a higher Cost than this member on your stage, this member gets +3 Blades.",
    # [2] PL!HS-bp2-005-R＋
    "{{toujyou.png|登場}}手札を1枚控え室に置いてもよい：自分のステージにほかのメンバーがいる場合、自分の控え室から『みらくらぱーく！』のカードを1枚手札に加える。\n{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}支払ってもよい：自分のステージのエリアすべてにメンバーが登場している場合、ライブ終了時まで、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[On Play] You may put 1 card from your hand into the waiting room: If you have another member on your stage, add 1 'Mira-Cra Park!' card from your waiting room to your hand.\n[Live Start] You may pay (E): If you have members in all areas of your stage, this member gets +2 Blades until the end of the live phase.",
    # [2] PL!HS-bp2-007-R＋
    "{{toujyou.png|登場}}このメンバーよりコストが低い『スリーズブーケ』のメンバーからバトンタッチして登場した場合、自分の控え室から『蓮ノ空』のライブカードを1枚手札に加える。\n{{live_start.png|ライブ開始時}}手札を1枚控え室に置いてもよい：これにより控え室に置いたカードがメンバーカードの場合、控え室に置いたカードと同じ名前を持つメンバー1人は、ライブ終了時まで、{{heart_04.png|heart04}}{{icon_blade.png|ブレード}}を得る。": "[On Play] If entered via Baton Touch from a 'Cerise Bouquet' member with lower Cost than this member, add 1 'Hasunosora' Live card from your waiting room to your hand.\n[Live Start] You may put 1 card from your hand into the waiting room: If the card put into the waiting room is a Member card, 1 member with the same name as that card gets [Heart 04] and +1 Blade until the end of the live phase.",
    # [2] PL!-bp3-004-R＋
    "{{toujyou.png|登場}}自分のステージにいるメンバー1人につき、カードを1枚引く。その後、手札を1枚控え室に置く。\n{{live_start.png|ライブ開始時}}自分の成功ライブカード置き場にカードがある場合、手札を1枚控え室に置いてもよい。そうした場合、自分の控え室から『μ's』のライブカードを1枚手札に加える。": "[On Play] Draw 1 card for each member on your stage. Then, put 1 card from your hand into the waiting room.\n[Live Start] If you have cards in your Success Live Area, you may put 1 card from your hand into the waiting room. If you do, add 1 'μ's' Live card from your waiting room to your hand.",
    # [2] PL!-bp3-008-R＋
    "{{kidou.png|起動}}{{turn1.png|ターン1回}}このメンバーをウェイトにする：自分の控え室から『μ's』のライブカードを1枚手札に加える。\n{{live_start.png|ライブ開始時}}『μ's』のメンバー1人をウェイトにしてもよい：ライブ終了時まで、{{heart_03.png|heart03}}{{heart_03.png|heart03}}を得る。": "[Activate] [Turn 1] Set this member to Waiting state: Add 1 'μ's' Live card from your waiting room to your hand.\n[Live Start] You may set 1 'μ's' member to Waiting state: This member gets [Heart 03][Heart 03] until the end of the live phase.",
    # [2] PL!-bp4-002-R＋
    "{{jyouji.png|常時}}自分のライブ中のライブカードに、{{live_start.png|ライブ開始時}}能力も{{live_success.png|ライブ成功時}}能力も持たないカードがあるかぎり、{{heart_06.png|heart06}}{{heart_06.png|heart06}}を得る。\n{{kidou.png|起動}}{{turn1.png|ターン1回}}手札を2枚控え室に置く：自分の控え室から『μ's』のライブカードを1枚手札に加える。この能力は、自分の成功ライブカード置き場にあるカードのスコアの合計が６以上の場合のみ起動できる。": "[Continuous] As long as you have a Live card in progress with no [Live Start] or [Live Success] abilities, this member gets [Heart 06][Heart 06].\n[Activate] [Turn 1] Put 2 cards from your hand into the waiting room: Add 1 'μ's' Live card from your waiting room to your hand. This ability can only be used if the total Score of cards in your Success Live Area is 6 or more.",
    # [2] PL!N-bp4-007-R＋
    "{{toujyou.png|登場}}自分と相手はそれぞれ、自身の控え室からライブカードを1枚手札に加える。\n{{jyouji.png|常時}}自分と相手のエネルギーの合計が15枚以上あるかぎり、{{heart_02.png|heart02}}{{heart_02.png|heart02}}を得る。\n{{live_success.png|ライブ成功時}}自分と相手はそれぞれ、自身のエネルギーデッキから、エネルギーカードを1枚ウェイト状態で置く。": "[On Play] Both you and your opponent add 1 Live card from your own waiting room to your hand.\n[Continuous] As long as the total Energy of you and your opponent is 15 or more, this member gets [Heart 02][Heart 02].\n[Live Success] Both you and your opponent place 1 Energy card from your own Energy Deck into your Energy Area in Waiting state.",
    # [2] PL!N-bp4-010-R＋
    "{{toujyou.png|登場}}自分の成功ライブカード置き場にある『虹ヶ咲』のライブカードを1枚控え室に置いてもよい。そうした場合、自分の控え室にある『虹ヶ咲』のライブカードを1枚成功ライブカード置き場に置く。\n{{live_start.png|ライブ開始時}}自分のライブ中の『虹ヶ咲』のライブカードを1枚選ぶ。それと同じカード名のカードが自分の成功ライブカード置き場にある場合、ライブ終了時まで、{{heart_04.png|heart04}}を得る。": "[On Play] You may put 1 'Nijigasaki' Live card from your Success Live Area into the waiting room. If you do, put 1 'Nijigasaki' Live card from your waiting room into your Success Live Area.\n[Live Start] Choose 1 of your 'Nijigasaki' Live cards in progress. If there is a card with the same name in your Success Live Area, this member gets [Heart 04] until the end of the live phase.",
    # [2] PL!N-bp4-011-R＋
    "{{live_start.png|ライブ開始時}}手札のライブカードを1枚控え室に置いてもよい：好きなハートの色を1つ指定する。ライブ終了時まで、そのハートを1つ得る。\n{{live_success.png|ライブ成功時}}自分のデッキの上からカードを5枚控え室に置く。その後、自分の控え室にカード名の異なる『虹ヶ咲』のライブカードが3枚以上ある場合、自分の控え室から『虹ヶ咲』のライブカードを1枚手札に加える。": "[Live Start] You may put 1 Live card from your hand into the waiting room: Choose 1 Heart color. This member gets 1 Heart of the chosen color until the end of the live phase.\n[Live Success] Put the top 5 cards of your deck into the waiting room. Then, if you have 3 or more 'Nijigasaki' Live cards with different names in your waiting room, add 1 'Nijigasaki' Live card from your waiting room to your hand.",
    # [2] PL!SP-bp4-004-R＋
    "{{jyouji.png|常時}}このカードのプレイに際し、2人のメンバーとバトンタッチしてもよい。\n{{toujyou.png|登場}}{{center.png|センター}}『Liella!』のメンバー2人からバトンタッチして登場している場合、カードを2枚引き、自分の控え室にあるコスト4以下の『Liella!』のメンバーカード1枚を自分のステージのメンバーのいないエリアに登場させる。": "[Continuous] You may Baton Touch with 2 members when playing this card.\n[On Play] [Center] If entered via Baton Touch from 2 'Liella!' members, draw 2 cards and play 1 'Liella!' Member card with Cost 4 or less from your waiting room to an empty area on your stage.",
    # [2] PL!SP-bp4-005-R＋
    "{{toujyou.png|登場}}『Liella!』のメンバーからバトンタッチして登場しており、かつ自分のエネルギーが7枚以上ある場合、自分のエネルギーデッキから、エネルギーカードを2枚ウェイト状態で置く。\n{{jyouji.png|常時}}自分のエネルギーが10枚以上あるかぎり、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[On Play] If entered via Baton Touch from a 'Liella!' member and you have 7 or more Energy, place 2 Energy cards from your Energy Deck into your Energy Area in Waiting state.\n[Continuous] As long as you have 10 or more Energy, this member gets +3 Blades.",
    # [2] PL!SP-bp4-008-R＋
    "{{toujyou.png|登場}}【左サイド】カードを2枚引き、手札を1枚控え室に置く。\n{{toujyou.png|登場}}【右サイド】エネルギーを2枚アクティブにする。\n{{live_start.png|ライブ開始時}}このメンバーをポジションチェンジしてもよい。(このメンバーを今いるエリア以外のエリアに移動させる。そのエリアにメンバーがいる場合、そのメンバーはこのメンバーがいたエリアに移動させる。)": "[On Play] [Left Side] Draw 2 cards, then put 1 card from your hand into the waiting room.\n[On Play] [Right Side] Activate 2 Energy.\n[Live Start] You may Position Change this member. (Move this member to a different area. If a member is in that area, move that member to the area this member was in.)",
    # [2] PL!N-pb1-001-R
    "{{toujyou.png|登場}}手札を1枚控え室に置いてもよい：自分のステージにこのメンバー以外のコスト11のメンバーがいる場合、自分の控え室から『虹ヶ咲』のライブカードを1枚手札に加える。\n{{jyouji.png|常時}}自分のライブ中のライブカードが2枚以上あるかぎり、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[On Play] You may put 1 card from your hand into the waiting room: If you have a member with Cost 11 other than this member on your stage, add 1 'Nijigasaki' Live card from your waiting room to your hand.\n[Continuous] As long as you have 2 or more Live cards in progress, this member gets +2 Blades.",
    # [2] PL!N-pb1-002-R
    "{{toujyou.png|登場}}自分のエネルギー置き場にあるエネルギー2枚をこのメンバーの下に置いてもよい。\n{{jyouji.png|常時}}このメンバーの下にエネルギーカードが2枚以上置かれているかぎり、ライブの合計スコアを＋１する。\n(メンバーがステージから離れたとき、下に置かれているエネルギーカードはエネルギーデッキに戻す。)": "[On Play] You may put 2 Energy using cards from your Energy Area under this member.\n[Continuous] As long as there are 2 or more Energy cards under this member, Live Score +1.\n(When the member leaves the stage, return the underlying Energy cards to the Energy Deck.)",
    # [2] PL!N-pb1-004-R
    "{{jyouji.png|常時}}このターンにこのメンバーが移動していないかぎり、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。\n{{live_start.png|ライブ開始時}}自分のデッキの一番上のカードを公開する。公開したカードがコスト9以下のメンバーカードの場合、公開したカードを手札に加え、このメンバーはポジションチェンジする。それ以外の場合、公開したカードを控え室に置く。": "[Continuous] As long as this member has not moved this turn, this member gets +2 Blades.\n[Live Start] Reveal the top card of your deck. If it is a Member card with Cost 9 or less, add it to your hand and Position Change this member. Otherwise, put the revealed card into the waiting room.",
    # [2] PL!N-pb1-008-R
    "{{jyouji.png|常時}}自分のステージにウェイト状態の『虹ヶ咲』のメンバーがいるかぎり、手札にあるこのメンバーカードのコストは2減る。\n{{toujyou.png|登場}}自分のステージにいるメンバー1人か、エネルギーを2枚アクティブにする。": "[Continuous] As long as you have a Waiting state 'Nijigasaki' member on your stage, the Cost of this member card in your hand is reduced by 2.\n[On Play] Activate 1 member on your stage or 2 Energy.",
    # [2] PL!N-pb1-010-R
    "{{toujyou.png|登場}}以下から1つを選ぶ。\n・エネルギーを1枚アクティブにする。\n・自分の控え室にある『虹ヶ咲』のライブカードを2枚まで好きな順番でデッキの上に置く。": "[On Play] Choose 1 of the following:\n- Activate 1 Energy.\n- Put up to 2 'Nijigasaki' Live cards from your waiting room on top of your deck in any order.",
    # [2] PL!N-pb1-011-R
    "{{jyouji.png|常時}}このメンバーの下にあるエネルギーカード1枚につき、{{icon_blade.png|ブレード}}を得る。\n{{kidou.png|起動}}{{turn1.png|ターン1回}}自分のエネルギー置き場にあるエネルギー1枚をこのメンバーの下に置く：自分の控え室から『虹ヶ咲』のライブカードを1枚手札に加える。\n(メンバーがステージから離れたとき、下に置かれているエネルギーカードはエネルギーデッキに戻す。)": "[Continuous] This member gets +1 Blade for each Energy card under it.\n[Activate] [Turn 1] Put 1 Energy from your Energy Area under this member: Add 1 'Nijigasaki' Live card from your waiting room to your hand.\n(When the member leaves the stage, return the underlying Energy cards to the Energy Deck.)",
    # [2] PL!N-pb1-012-R
    "{{jidou.png|自動}}{{turn1.png|ターン1回}}自分のステージにこのメンバー以外のコスト11のメンバーが登場したとき、自分のエネルギーデッキから、エネルギーカードを1枚ウェイト状態で置く。\n{{live_success.png|ライブ成功時}}エールにより公開された自分のカードの中から、『虹ヶ咲』のメンバーカードを1枚手札に加える。": "[Auto] [Turn 1] When a member with Cost 11 other than this member enters your stage, place 1 Energy card from your Energy Deck into your Energy Area in Waiting state.\n[Live Success] Add 1 'Nijigasaki' Member card revealed by your Yell to your hand.",
    # [1] PL!-sd1-001-SD
    "{{toujyou.png|登場}}自分の成功ライブカード置き場にカードが2枚以上ある場合、自分の控え室からライブカードを1枚手札に加える。\n{{jyouji.png|常時}}自分の成功ライブカード置き場にあるカード1枚につき、{{icon_blade.png|ブレード}}を得る。": "[On Play] If you have 2 or more cards in your Success Live Area, add 1 Live card from your waiting room to your hand.\n[Continuous] This member gets +1 Blade for each card in your Success Live Area.",
    # [1] PL!-sd1-003-SD
    "{{toujyou.png|登場}}自分の控え室からコスト4以下の『μ's』のメンバーカードを1枚手札に加える。\n{{live_start.png|ライブ開始時}}手札を1枚控え室に置いてもよい：{{heart_01.png|heart01}}か{{heart_03.png|heart03}}か{{heart_06.png|heart06}}のうち、1つを選ぶ。ライブ終了時まで、選んだハートを1つ得る。": "[On Play] Add 1 'μ's' Member card with Cost 4 or less from your waiting room to your hand.\n[Live Start] You may put 1 card from your hand into the waiting room: Choose [Heart 01], [Heart 03], or [Heart 06]. This member gets the chosen Heart until the end of the live phase.",
    # [1] LL-PR-004-PR
    "{{live_start.png|ライブ開始時}}相手に何が好き？と聞く。\n回答がチョコミントかストロベリーフレイバーかクッキー＆クリームの場合、自分と相手は手札を1枚控え室に置く。\n回答があなたの場合、自分と相手はカードを1枚引く。\n回答がそれ以外の場合、ライブ終了時まで、自分と相手のステージにいるメンバーは{{icon_blade.png|ブレード}}を得る。": '[Live Start] Ask your opponent "What do you like?"\nIf the answer is "Choco Mint", "Strawberry Flavor", or "Cookies & Cream", both you and your opponent put 1 card from your hand into the waiting room.\nIf the answer is "You", both you and your opponent draw 1 card.\nIf the answer is anything else, members on both your and your opponent\'s stages get +1 Blade until the end of the live phase.',
    # [1] LL-bp1-001-R＋
    "{{toujyou.png|登場}}自分の控え室からメンバーカードを1枚手札に加える。\n{{live_start.png|ライブ開始時}}手札の「上原歩夢」と「澁谷かのん」と「日野下花帆」を、好きな組み合わせで合計3枚、控え室に置いてもよい：ライブ終了時まで、「{{jyouji.png|常時}}ライブの合計スコアを＋３する。」を得る。\n（手札のこのカードもこの効果で控え室に置ける。）": "[On Play] Add 1 Member card from your waiting room to your hand.\n[Live Start] You may put a total of 3 'Ayumu Uehara', 'Kanon Shibuya', and 'Kaho Hinoshita' cards from your hand into the waiting room in any combination: This member gets \"[Continuous] Live Score +3\" until the end of the live phase.\n(This card in your hand can also be put into the waiting room by this effect.)",
    # [1] PL!N-bp1-026-L
    "{{live_success.png|ライブ成功時}}ライブの合計スコアが相手より高い場合、エールにより公開された自分のカードの中から、『虹ヶ咲』のカードを1枚手札に加える。\n\n(必要ハートを確認する時、エールで出た{{icon_b_all.png|ALLブレード}}は任意の色のハートとして扱う。)": "[Live Success] If your total Live Score is higher than your opponent's, add 1 'Nijigasaki' card revealed by your Yell to your hand.\n\n(When checking required Hearts, [ALL Blade] revealed by Yell is treated as a Heart of any color.)",
    # [1] PL!N-bp1-027-L
    "{{live_start.png|ライブ開始時}}自分のステージにいる『虹ヶ咲』のメンバーが持つ{{heart_01.png|heart01}}、{{heart_04.png|heart04}}、{{heart_05.png|heart05}}、{{heart_02.png|heart02}}、{{heart_03.png|heart03}}、{{heart_06.png|heart06}}のうち1色につき、このカードのスコアを＋１する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Start] Live Score +1 for this card for each color among [Heart 01], [Heart 04], [Heart 05], [Heart 02], [Heart 03], and [Heart 06] held by 'Nijigasaki' members on your stage.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!N-bp1-028-L
    "{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：自分のステージに『虹ヶ咲』のメンバーがいる場合、このカードのスコアを＋１する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Start] You may pay (E)(E): If you have a 'Nijigasaki' member on your stage, Live Score +1 for this card.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!N-bp1-029-L
    "{{live_start.png|ライブ開始時}}自分のライブ中のカードが3枚以上ある場合、このカードのスコアを＋２する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Start] If you have 3 or more Live cards in progress, Live Score +2 for this card.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!SP-bp1-023-L
    "{{live_success.png|ライブ成功時}}ライブの合計スコアが相手より高い場合、自分のエネルギーデッキから、エネルギーカードを1枚ウェイト状態で置く。\n\n(エールで出た{{icon_score.png|スコア}}1つにつき、成功したライブのスコアの合計に1を加算する。)": "[Live Success] If your total Live Score is higher than your opponent's, place 1 Energy card from your Energy Deck into your Energy Area in Waiting state.\n\n(For each [Score] icon revealed by Yell, add 1 to the total Score of the succeeded Live.)",
    # [1] PL!SP-bp1-024-L
    "{{live_start.png|ライブ開始時}}ライブ終了時まで、自分のステージにいる「澁谷かのん」1人は{{heart_05.png|heart05}}{{icon_blade.png|ブレード}}を、「唐可可」1人は{{heart_01.png|heart01}}{{icon_blade.png|ブレード}}を得る。\n{{live_success.png|ライブ成功時}}自分のステージに「澁谷かのん」と「唐可可」がいる場合、カードを1枚引く。\n\n(必要ハートを確認する時、エールで出た{{icon_b_all.png|ALLブレード}}は任意の色のハートとして扱う。)": "[Live Start] Until the end of the live phase, 1 'Kanon Shibuya' on your stage gets [Heart 05] and +1 Blade, and 1 'Keke Tang' on your stage gets [Heart 01] and +1 Blade.\n[Live Success] If you have both 'Kanon Shibuya' and 'Keke Tang' on your stage, draw 1 card.\n\n(When checking required Hearts, [ALL Blade] revealed by Yell is treated as a Heart of any color.)",
    # [1] PL!SP-bp1-026-L
    "{{live_start.png|ライブ開始時}}自分の、ステージと控え室に名前の異なる『Liella!』のメンバーが5人以上いる場合、このカードを使用するためのコストは{{heart_02.png|heart02}}{{heart_02.png|heart02}}{{heart_03.png|heart03}}{{heart_03.png|heart03}}{{heart_06.png|heart06}}{{heart_06.png|heart06}}になる。\n\n(必要ハートを確認する時、エールで出た{{icon_b_all.png|ALLブレード}}は任意の色のハートとして扱う。)": "[Live Start] If you have 5 or more 'Liella!' members with different names between your stage and waiting room, the Cost to use this card becomes [Heart 02][Heart 02][Heart 03][Heart 03][Heart 06][Heart 06].\n\n(When checking required Hearts, [ALL Blade] revealed by Yell is treated as a Heart of any color.)",
    # [1] PL!SP-bp1-027-L
    "{{live_start.png|ライブ開始時}}自分のエネルギーが12枚以上ある場合、このカードのスコアを＋１する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Start] If you have 12 or more Energy, Live Score +1 for this card.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!HS-bp1-021-L
    "{{live_success.png|ライブ成功時}}エールにより公開された自分のカードの中から、『蓮ノ空』のライブカードを1枚手札に加える。\n\n(必要ハートを確認する時、エールで出た{{icon_b_all.png|ALLブレード}}は任意の色のハートとして扱う。)": "[Live Success] Add 1 'Hasunosora' Live card revealed by your Yell to your hand.\n\n(When checking required Hearts, [ALL Blade] revealed by Yell is treated as a Heart of any color.)",
    # [1] PL!HS-bp1-022-L
    "{{live_success.png|ライブ成功時}}エールにより公開された自分のカードの中に『蓮ノ空』のメンバーカードが10枚以上ある場合、このカードのスコアを＋１する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Success] If 10 or more 'Hasunosora' Member cards are revealed by your Yell, Live Score +1 for this card.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!HS-bp1-023-L
    "{{live_success.png|ライブ成功時}}ライブの合計スコアが相手より高く、かつ自分のステージに『蓮ノ空』のメンバーがいる場合、自分のエネルギーデッキから、エネルギーカードを1枚ウェイト状態で置く。\n\n(必要ハートを確認する時、エールで出た{{icon_b_all.png|ALLブレード}}は任意の色のハートとして扱う。)": "[Live Success] If your total Live Score is higher than your opponent's and you have a 'Hasunosora' member on your stage, place 1 Energy card from your Energy Deck into your Energy Area in Waiting state.\n\n(When checking required Hearts, [ALL Blade] revealed by Yell is treated as a Heart of any color.)",
    # [1] PL!N-sd1-001-SD
    "{{toujyou.png|登場}}自分のデッキの上からカードを5枚見る。その中から『虹ヶ咲』のライブカードを1枚まで公開して手札に加えてもよい。残りを控え室に置く。\n{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}支払ってもよい：ライブ終了時まで、自分のステージにいるほかの『虹ヶ咲』のメンバーは{{icon_blade.png|ブレード}}を得る。": "[On Play] Look at the top 5 cards of your deck. You may reveal up to 1 'Nijigasaki' Live card from among them and add it to your hand. Put the rest into the waiting room.\n[Live Start] You may pay (E): Other 'Nijigasaki' members on your stage get +1 Blade until the end of the live phase.",
    # [1] PL!N-sd1-010-SD
    "{{toujyou.png|登場}}カードを2枚引き、手札を1枚控え室に置く。\n{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：ライブ終了時まで、{{heart_04.png|heart04}}を得る。": "[On Play] Draw 2 cards, then put 1 card from your hand into the waiting room.\n[Live Start] You may pay (E)(E): This member gets [Heart 04] until the end of the live phase.",
    # [1] PL!N-sd1-028-SD
    "{{live_start.png|ライブ開始時}}自分のステージにいるメンバーが持つ{{icon_blade.png|ブレード}}の合計が10以上の場合、このカードのスコアを＋１する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Start] If the total number of Blades held by members on your stage is 10 or more, Live Score +1 for this card.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!SP-sd1-002-SD
    "{{toujyou.png|登場}}手札からコスト4以下の『Liella!』のメンバーカードを1枚ステージに登場させてもよい。\n（この効果で既にメンバーがいるエリアにも登場できる。ただし、このターンにステージに登場したメンバーがいるエリアには登場できない。）": "[On Play] You may play 1 'Liella!' Member card with Cost 4 or less from your hand to the stage.\n(You can play it even in an area occupied by a member. However, you cannot play it in an area where a member has already entered this turn.)",
    # [1] PL!SP-sd1-026-SD
    "{{live_start.png|ライブ開始時}}自分のエネルギーが9枚以上ある場合、このカードのスコアを＋１する。\n\n(エールをすべて行った後、エールで出た{{icon_draw.png|ドロー}}1つにつき、カードを1枚引く。)": "[Live Start] If you have 9 or more Energy, Live Score +1 for this card.\n\n(After all Yells are performed, draw 1 card for each [Draw] icon revealed by Yell.)",
    # [1] PL!SP-pb1-001-P＋
    "{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払わないかぎり、自分の手札を2枚控え室に置く。\n{{live_success.png|ライブ成功時}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：ライブの合計スコアを＋１する。": "[Live Start] Unless you pay (E)(E), put 2 cards from your hand into the waiting room.\n[Live Success] You may pay (E)(E)(E)(E)(E)(E): Live Score +1.",
    # [1] PL!SP-pb1-006-P＋
    "{{jidou.png|自動}}このメンバーが登場か、エリアを移動するたび、ライブ終了時まで、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。\n(対戦相手のカードの効果でも発動する。)": "[Auto] Whenever this member enters the stage or moves to a different area, this member gets +2 Blades until the end of the live phase.\n(Also activates by your opponent's card effects.)",
    # [1] PL!SP-pb1-020-N
    "{{jidou.png|自動}}このメンバーがエリアを移動するたび、カードを1枚引く。\n(対戦相手のカードの効果でも発動する。)": "[Auto] Whenever this member moves to a different area, draw 1 card.\n(Also activates by your opponent's card effects.)",
    # [1] PL!S-bp2-024-L
    "{{jyouji.png|常時}}このカードは成功ライブカード置き場に置くことができない。\n{{live_success.png|ライブ成功時}}カードを2枚引き、手札を1枚控え室に置く。": "[Continuous] This card cannot be put into the Success Live Area.\n[Live Success] Draw 2 cards, then put 1 card from your hand into the waiting room.",
    # [1] PL!HS-bp2-020-L
    "{{jyouji.png|常時}}すべての領域にあるこのカードは『スリーズブーケ』、『DOLLCHESTRA』、『みらくらぱーく！』として扱う。\n{{live_start.png|ライブ開始時}}自分のステージにいる名前の異なる『蓮ノ空』のメンバー1人につき、このカードのスコアを＋２する。": "[Continuous] This card is treated as 'Cerise Bouquet', 'DOLLCHESTRA', and 'Mira-Cra Park!' in all areas.\n[Live Start] Live Score +2 for this card for each 'Hasunosora' member with a different name on your stage.",
    # [1] LL-bp2-001-R＋
    "{{jyouji.png|常時}}手札にあるこのメンバーカードのコストは、このカード以外の自分の手札1枚につき、1少なくなる。\n{{jyouji.png|常時}}このメンバーはバトンタッチで控え室に置けない。\n{{live_start.png|ライブ開始時}}手札の「渡辺曜」と「鬼塚夏美」と「大沢瑠璃乃」を、好きな枚数控え室に置いてもよい：ライブ終了時まで、これによって控え室に置いた枚数1枚につき、{{icon_blade.png|ブレード}}を得る。\n（手札のこのカードもこの効果で控え室に置ける。）": "[Continuous] The Cost of this member card in your hand is reduced by 1 for each other card in your hand.\n[Continuous] This member cannot be put into the waiting room by Baton Touch.\n[Live Start] You may put any number of 'You Watanabe', 'Natsumi Onitsuka', and 'Rurino Osawa' cards from your hand into the waiting room: This member gets +1 Blade for each card put into the waiting room by this effect until the end of the live phase.\n(This card in your hand can also be put into the waiting room by this effect.)",
    # [1] PL!S-pb1-003-P＋
    "{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：ライブ終了時まで、このメンバーが元々持つハートはすべて{{heart_04.png|heart04}}になる。{{live_success.png|ライブ成功時}}エールにより公開された自分のカードの中から、ライブカードを1枚手札に加える。": "[Live Start] You may pay (E)(E): All base Hearts of this member become [Heart 04] until the end of the live phase. [Live Success] Add 1 Live card revealed by your Yell to your hand.",
    # [1] PL!-bp3-009-R＋
    "{{toujyou.png|登場}}自分のステージにコスト13以上のメンバーがいる場合、カードを1枚引く。\n{{kidou.png|起動}}{{turn1.png|ターン1回}}このメンバーをウェイトにする：{{heart_01.png|heart01}}か{{heart_03.png|heart03}}か{{heart_06.png|heart06}}のうち、1つを選ぶ。ライブ終了時まで、選んだハートを1つ得る。": "[On Play] If you have a member with Cost 13 or more on your stage, draw 1 card.\n[Activate] [Turn 1] Set this member to Waiting state: Choose [Heart 01], [Heart 03], or [Heart 06]. This member gets the chosen Heart until the end of the live phase.",
    # [1] PL!-bp3-024-L
    "{{live_start.png|ライブ開始時}}自分の成功ライブカード置き場にカードがある場合、{{heart_01.png|heart01}}か{{heart_03.png|heart03}}か{{heart_06.png|heart06}}のうち、1つを選ぶ。ライブ終了時まで、自分のステージにいる『μ's』のメンバー1人は、選んだハートを1つ得る。\n{{live_start.png|ライブ開始時}}自分の成功ライブカード置き場にカードが2枚以上ある場合、このカードのスコアを＋１する。": "[Live Start] If you have cards in your Success Live Area, choose [Heart 01], [Heart 03], or [Heart 06]. 1 'μ's' member on your stage gets the chosen Heart until the end of the live phase.\n[Live Start] If you have 2 or more cards in your Success Live Area, Live Score +1 for this card.",
    # [1] PL!-bp3-026-L
    "{{live_start.png|ライブ開始時}}手札を2枚控え室に置いてもよい：ライブ終了時まで、自分のステージにいるメンバー1人は、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。\n{{live_success.png|ライブ成功時}}自分のステージにいるメンバーが持つハートの総数が、相手のステージにいるメンバーが持つハートの総数より多い場合、このカードのスコアを＋１する。": "[Live Start] You may put 2 cards from your hand into the waiting room: 1 member on your stage gets +3 Blades until the end of the live phase.\n[Live Success] If the total number of Hearts held by members on your stage is greater than the total number of Hearts held by members on your opponent's stage, Live Score +1 for this card.",
    # [1] PL!S-bp3-003-R＋
    "{{toujyou.png|登場}}手札のライブカードを1枚控え室に置いてもよい：カードを3枚引く。\n{{live_start.png|ライブ開始時}}手札を2枚まで控え室に置いてもよい：ライブ終了時まで、これによって控え室に置いたカード1枚につき、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[On Play] You may put 1 Live card from your hand into the waiting room: Draw 3 cards.\n[Live Start] You may put up to 2 cards from your hand into the waiting room: This member gets +2 Blades for each card put into the waiting room by this effect until the end of the live phase.",
    # [1] PL!S-bp3-024-L
    "{{live_start.png|ライブ開始時}}自分のステージのセンターエリアにコスト9以上の『Aqours』のメンバーがいる場合、以下から1つを選ぶ。\n・ライブ終了時まで、自分のステージにいるメンバー1人は、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。\n・相手のステージにいるコスト4以下のメンバー1人をウェイトにする。": "[Live Start] If you have an 'Aqours' member with Cost 9 or more in your Center Area, choose 1 of the following:\n- 1 member on your stage gets +2 Blades until the end of the live phase.\n- Set 1 member with Cost 4 or less on your opponent's stage to Waiting state.",
    # [1] PL!N-bp3-005-R＋
    "{{jidou.png|自動}}このターン、自分のステージにメンバーが3回登場したとき、手札が5枚になるまでカードを引く。\n{{live_start.png|ライブ開始時}}このターン、自分のステージにメンバーが2回以上登場している場合、ライブ終了時まで、「{{jyouji.png|常時}}ライブの合計スコアを＋１する。」を得る。": '[Auto] When a member enters your stage for the 3rd time this turn, draw cards until you have 5 cards in your hand.\n[Live Start] If members have entered your stage 2 or more times this turn, this member gets "[Continuous] Live Score +1" until the end of the live phase.',
    # [1] PL!N-bp3-008-R＋
    "{{kidou.png|起動}}{{turn1.png|ターン1回}}このメンバー以外の『虹ヶ咲』のメンバー1人をウェイトにする：カードを1枚引く。\n{{live_start.png|ライブ開始時}}手札を2枚控え室に置いてもよい：自分のステージにいるこのメンバー以外のウェイト状態のメンバー1人をアクティブにする。そうした場合、ライブ終了時まで、これによりアクティブにしたメンバーと、このメンバーは、それぞれ{{heart_04.png|heart04}}を得る。": "[Activate] [Turn 1] Set 1 'Nijigasaki' member other than this member to Waiting state: Draw 1 card.\n[Live Start] You may put 2 cards from your hand into the waiting room: Activate 1 Waiting state member on your stage other than this member. If you do, that member and this member both get [Heart 04] until the end of the live phase.",
    # [1] LL-bp3-001-R＋
    "{{kidou.png|起動}}{{turn1.png|ターン1回}}自分の控え室にある「園田海未」と「津島善子」と「天王寺璃奈」を、合計6枚をシャッフルしてデッキの一番下に置く：エネルギーを6枚までアクティブにする。\n{{live_start.png|ライブ開始時}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}{{icon_energy.png|E}}支払ってもよい：ライブ終了時まで、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[Activate] [Turn 1] Shuffle a total of 6 'Umi Sonoda', 'Yoshiko Tsushima', and 'Rina Tennoji' cards from your waiting room into the bottom of your deck: Activate up to 6 Energy.\n[Live Start] You may pay (E)(E)(E)(E)(E)(E): This member gets +3 Blades until the end of the live phase.",
    # [1] PL!-pb1-002-P＋
    "{{toujyou.png|登場}}/{{live_start.png|ライブ開始時}}このメンバーをウェイトにしてもよい：自分のステージにいるメンバーが『BiBi』のみの場合、相手のステージにいる元々持つ{{icon_blade.png|ブレード}}の数が3つ以下のメンバー1人をウェイトにする。\n{{jyouji.png|常時}}相手のステージにいるウェイト状態のメンバー1人につき、{{heart_06.png|heart06}}を得る。": "[On Play] / [Live Start] You may set this member to Waiting state: If you have only 'BiBi' members on your stage, set 1 member on your opponent's stage with 3 or fewer base Blades to Waiting state.\n[Continuous] This member gets [Heart 06] for each Waiting state member on your opponent's stage.",
    # [1] PL!-pb1-009-P＋
    "{{toujyou.png|登場}}相手のステージにいる元々持つ{{icon_blade.png|ブレード}}の数が1つ以下のメンバー1人をウェイトにする。\n{{toujyou.png|登場}}このターン、自分と相手のステージにいるメンバーは、効果によってはアクティブにならない。": "[On Play] Set 1 member on your opponent's stage with 1 or fewer base Blades to Waiting state.\n[On Play] This turn, members on both your and your opponent's stages cannot be activated by card effects.",
    # [1] PL!-pb1-015-P＋
    "{{toujyou.png|登場}}/{{live_start.png|ライブ開始時}}{{center.png|センター}}『BiBi』のメンバー1人をウェイトにしてもよい：相手は、自身のステージにいるアクティブ状態のメンバー1人をウェイトにする。（この能力はセンターエリアにいる場合のみ発動する。）\n{{jidou.png|自動}}{{turn1.png|ターン1回}}自分のカードの効果によって、相手のステージにいるアクティブ状態のコスト4以下のメンバーがウェイト状態になったとき、カードを1枚引く。": "[On Play] / [Live Start] [Center] You may set 1 'BiBi' member to Waiting state: Your opponent sets 1 of their Active state members to Waiting state. (Activates only when in the Center Area.)\n[Auto] [Turn 1] When an opponent's Active state member with Cost 4 or less becomes Waiting state due to your card effect, draw 1 card.",
    # [1] PL!-pb1-030-L
    "{{live_start.png|ライブ開始時}}相手のステージにウェイト状態のメンバーがいる場合、このカードを成功させるための必要ハートを{{heart_00.png|heart0}}{{heart_00.png|heart0}}減らす。\n{{live_success.png|ライブ成功時}}自分のステージに名前の異なる『BiBi』のメンバーが2人以上いる場合、自分の控え室から『BiBi』のメンバーカードを1枚手札に加える。": "[Live Start] If there is a Waiting state member on your opponent's stage, reduce the Hearts required to succeed this card by [Heart 00][Heart 00].\n[Live Success] If you have 2 or more 'BiBi' members with different names on your stage, add 1 'BiBi' Member card from your waiting room to your hand.",
    # [1] PL!-bp4-002-SEC
    "{{jyouji.png|常時}}自分のライブ中のライブカードに、{{live_start.png|ライブ開始時}}能力も{{live_success.png|ライブ成功時}}能力も持たないカードがあるかぎり、{{heart_06.png|heart06}}{{heart_06.png|heart06}}を得る。\n{{kidou.png|起動}}{{turn1.png|ターン1回}}手札を2枚控え室に置く：自分の控え室から『μ's』のライブカードを1枚手札に加える。この能力は、自分の成功ライブカード置き場にあるカードのスコアの合計が７以上の場合のみ起動できる。": "[Continuous] As long as you have a Live card in progress with no [Live Start] or [Live Success] abilities, this member gets [Heart 06][Heart 06].\n[Activate] [Turn 1] Put 2 cards from your hand into the waiting room: Add 1 'μ's' Live card from your waiting room to your hand. This ability can only be used if the total Score of cards in your Success Live Area is 7 or more.",
    # [1] PL!-bp4-020-L
    "{{live_start.png|ライブ開始時}}自分のステージにいるメンバーが『μ's』のみの場合、自分のステージにいるメンバー1人をポジションチェンジさせてもよい。\n{{jyouji.png|常時}}このカードが自分の成功ライブカード置き場にあるかぎり、自分のセンターエリアにいる『μ's』のメンバーは{{icon_blade.png|ブレード}}を得る。": "[Live Start] If you have only 'μ's' members on your stage, you may Position Change 1 member on your stage.\n[Continuous] As long as this card is in your Success Live Area, 'μ's' member in your Center Area gets +1 Blade.",
    # [1] PL!N-bp4-025-L
    "{{live_start.png|ライブ開始時}}ライブ終了時まで、エールによって公開される自分のカードが持つ[桃ブレード]、[赤ブレード]、[黄ブレード]、[緑ブレード]、[紫ブレード]、{{icon_b_all.png|ALLブレード}}は、すべて[青ブレード]になる。\n{{live_success.png|ライブ成功時}}エールにより公開された自分の『虹ヶ咲』のメンバーカードが持つハートの中に{{heart_01.png|heart01}}、{{heart_02.png|heart02}}、{{heart_03.png|heart03}}、{{heart_04.png|heart04}}、{{heart_05.png|heart05}}、{{heart_06.png|heart06}}がある場合、このカードのスコアを＋１する。": "[Live Start] Until the end of the live phase, all [Pink Blade], [Red Blade], [Yellow Blade], [Green Blade], [Purple Blade], and [ALL Blade] on cards revealed by your Yell become [Blue Blade].\n[Live Success] If 'Nijigasaki' Member cards revealed by your Yell have [Heart 01], [Heart 02], [Heart 03], [Heart 04], [Heart 05], or [Heart 06], Live Score +1 for this card.",
    # [1] PL!N-bp4-026-L
    "{{jidou.png|自動}}自分のメインフェイズにこのカードが控え室から手札に加えられたとき、自分の手札からカード名が「DIVE!」のライブカード1枚を表向きでライブカード置き場に置いてもよい。そうした場合、次のライブカードセットフェイズで自分がライブカード置き場に置けるカード枚数の上限が1枚減る。\n{{jidou.png|自動}}このカードが表向きでライブカード置き場に置かれたとき、ライブ終了時まで、自分のステージにいる『虹ヶ咲』のメンバー1人は、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[Auto] When this card is added to your hand from the waiting room during your Main Phase, you may put 1 'DIVE!' Live card from your hand face up into your Live Area. If you do, the maximum number of Live cards you can set during your next Live Card Set Phase is reduced by 1.\n[Auto] When this card is placed face up in the Live Area, 1 'Nijigasaki' member on your stage gets +2 Blades until the end of the live phase.",
    # [1] PL!N-bp4-030-L
    "{{live_success.png|ライブ成功時}}以下から1つを選ぶ。自分の成功ライブカード置き場に『虹ヶ咲』のカードがある場合、代わりに1つ以上を選ぶ。\n・自分のエネルギーデッキから、エネルギーカードを1枚ウェイト状態で置く。\n・自分の控え室からメンバーカードを1枚手札に加える。": "[Live Success] Choose 1 of the following. If you have a 'Nijigasaki' card in your Success Live Area, choose 1 or more instead.\n- Place 1 Energy card from your Energy Deck into your Energy Area in Waiting state.\n- Add 1 Member card from your waiting room to your hand.",
    # [1] PL!SP-bp4-023-L
    "{{live_start.png|ライブ開始時}}ライブ終了時まで、自分のステージにいる、「澁谷かのん」「ウィーン・マルガレーテ」「鬼塚冬毬」のうちのメンバー1人と、これにより選んだメンバー以外の『Liella!』のメンバー1人は、{{icon_blade.png|ブレード}}を得る。\n{{live_start.png|ライブ開始時}}ライブ終了時まで、エールによって公開される自分のカードが持つ[桃ブレード]、[赤ブレード]、[黄ブレード]、[緑ブレード]、[青ブレード]、{{icon_b_all.png|ALLブレード}}は、すべて[紫ブレード]になる。": "[Live Start] Choose 1 'Kanon Shibuya', 'Wien Margarete', or 'Tomari Onitsuka' on your stage. That member and 1 other 'Liella!' member on your stage get +1 Blade until the end of the live phase.\n[Live Start] Until the end of the live phase, all [Pink Blade], [Red Blade], [Yellow Blade], [Green Blade], [Blue Blade], and [ALL Blade] on cards revealed by your Yell become [Purple Blade].",
    # [1] PL!SP-bp4-024-L
    "{{live_start.png|ライブ開始時}}自分のセンターエリアにいる『Liella!』のメンバーのコストが、相手のセンターエリアにいるメンバーより高い場合、このカードのスコアを＋１する。\n{{live_start.png|ライブ開始時}}自分のステージの左サイドエリアにいる『Liella!』のメンバーが{{heart_02.png|heart02}}を3つ以上持つ場合、そのメンバーは、ライブ終了時まで、{{icon_blade.png|ブレード}}{{icon_blade.png|ブレード}}を得る。": "[Live Start] If the Cost of the 'Liella!' member in your Center Area is higher than the Cost of the member in your opponent's Center Area, Live Score +1 for this card.\n[Live Start] If the 'Liella!' member in your Left Side Area has 3 or more [Heart 02], that member gets +2 Blades until the end of the live phase.",
    # [1] PL!SP-bp4-025-L
    "{{live_start.png|ライブ開始時}}ライブ終了時まで、自分のステージのセンターエリアにいる『Liella!』のメンバーが元々持つ{{icon_blade.png|ブレード}}の数は3つになる。\n{{live_success.png|ライブ成功時}}自分のステージのセンターエリアにいる『Liella!』のメンバーが、このターン中に移動している場合、このカードのスコアを＋１する。": "[Live Start] Until the end of the live phase, the number of base Blades of the 'Liella!' member in your Center Area becomes 3.\n[Live Success] If the 'Liella!' member in your Center Area has moved this turn, Live Score +1 for this card.",
    # [1] PL!SP-bp4-026-L
    "{{live_success.png|ライブ成功時}}エールにより公開された自分のカードの中に名前が異なる『Liella!』のメンバーカードが5枚以上ある場合、このカードのスコアを＋１する。\n{{live_success.png|ライブ成功時}}自分のエネルギーが11枚以上ある場合、カードを2枚引き、手札を1枚控え室に置く。": "[Live Success] If 5 or more 'Liella!' Member cards with different names are revealed by your Yell, Live Score +1 for this card.\n[Live Success] If you have 11 or more Energy, draw 2 cards, then put 1 card from your hand into the waiting room.",
}


def normalize(text):
    text = re.sub(r"\{\{.*?\|(.*?)\}\}", r"\1", text)
    text = re.sub(r"\{\{.*?\}\}", "", text)
    text = re.sub(r"[・、。：！\!？\?\s\(\)（）/]", "", text)
    text = text.replace('"', "").replace("「", "").replace("」", "")
    return text


with open("data/cards.json", "r", encoding="utf-8") as f:
    cards = json.load(f)

with open("data/manual_translations_en.json", "r", encoding="utf-8") as f:
    existing = json.load(f)

# Create normalized map
norm_map = {normalize(k): v for k, v in translations_map.items()}

count = 0
for cid, card in cards.items():
    text = card.get("ability")
    if not text or text == "なし":
        continue

    # Check if we have a translation for this text (normalized)
    norm = normalize(text)
    if norm in norm_map:
        if existing.get(cid) != norm_map[norm]:
            existing[cid] = norm_map[norm]
            count += 1

with open("data/manual_translations_en.json", "w", encoding="utf-8") as f:
    json.dump(existing, f, indent=4, ensure_ascii=False)

print(f"Updated {count} remaining translations in manual_translations_en.json")
