from enum import IntEnum


class ChoiceType(IntEnum):
    NONE = 0
    TARGET_HAND = 1
    TARGET_MEMBER = 2
    TARGET_MEMBER_SLOT = 3
    DISCARD_SELECT = 4
    MODAL = 5
    SELECT_MODE = 6
    CHOOSE_FORMATION = 7
    COLOR_SELECT = 8
    SELECT_FROM_LIST = 9
    TARGET_OPPONENT_MEMBER = 10
    SELECT_SWAP_SOURCE = 11
    TARGET_SUCCESS_LIVES = 12
    TARGET_DISCARD = 13
    TARGET_REMOVED = 14
    TARGET_DECK = 15
    TARGET_LIVE = 16
