# @generated by tools/sync_metadata.py on 2026-03-20T23:30:01.815535

from enum import IntEnum

from .generated_metadata import CONDITIONS, COSTS, OPCODES


def _build_opcode_enum() -> IntEnum:
    """Build a real IntEnum from generated metadata."""
    members = dict(OPCODES)
    members.update({name: value for name, value in COSTS.items()})
    members.update({f"CHECK_{name}": value for name, value in CONDITIONS.items()})
    members.update({f"COST_{name}": value for name, value in COSTS.items()})
    return IntEnum("Opcode", members, module=__name__)


Opcode = _build_opcode_enum()
