import os
import re
from collections import defaultdict

def extract_rules_from_text(file_path):
    rules = set()
    # Pattern to match rule numbers at the start of a line or after a newline
    # e.g. "1. ", "1.1. ", "9.5.1. "
    pattern = re.compile(r'^\s*(\d+(\.\d+)+)\.?\s', re.MULTILINE)
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        matches = pattern.findall(content)
        for match in matches:
            rules.add(match[0])
    
    # Also catch top level sections like "1. ", "2. "
    top_pattern = re.compile(r'^\s*(\d+)\.\s', re.MULTILINE)
    matches = top_pattern.findall(content)
    for match in matches:
        rules.add(match)
        
    return rules

def audit_codebase(src_dir, rules):
    coverage = defaultdict(int)
    missing = set()
    # Search for Rule X.Y.Z in comments
    rule_patterns = {rule: re.compile(r'Rule\s+' + re.escape(rule)) for rule in rules}
    # Pattern to detect rules explicitly marked as not present
    missing_marker = re.compile(r'Rule\s+(\d+(\.\d+)*)\s+\((N/A|MISSING|NOT_PRESENT|NOT_IMPLEMENTED)\)')
    
    for root, dirs, files in os.walk(src_dir):
        for file in files:
            if file.endswith('.rs'):
                path = os.path.join(root, file)
                with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                    # Check for explicit missing markers first
                    for match in missing_marker.finditer(content):
                        rule_id = match.group(1)
                        if rule_id in rules:
                            missing.add(rule_id)
                    
                    # Then count all references
                    for rule, pattern in rule_patterns.items():
                        count = len(pattern.findall(content))
                        if count > 0:
                            coverage[rule] += count
    return coverage, missing

def main():
    # Use relative paths from engine_rust_src
    rules_txt = os.path.join('..', 'docs', 'rules', 'rules.txt')
    src_dir = 'src'
    output_file = 'RULE_COVERAGE.md'
    
    if not os.path.exists(rules_txt):
        # Try absolute path fallback if running in a weird env
        rules_txt = r'c:\Users\trios\.gemini\antigravity\vscode\loveca-copy\docs\rules\rules.txt'

    all_rules = extract_rules_from_text(rules_txt)
    covered_rules, missing_rules = audit_codebase(src_dir, all_rules)
    
    sorted_rules = sorted(list(all_rules), key=lambda x: [int(s) for s in x.split('.')])
    
    total_rules = len(sorted_rules)
    covered_count = sum(1 for r in sorted_rules if covered_rules[r] > 0 and r not in missing_rules)
    missing_count = len(missing_rules)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("<!-- AUTO-GENERATED BY tools/rule_audit.py - DO NOT EDIT MANUALLY -->\n")
        f.write("# Rule Coverage Audit\n\n")
        f.write(f"- **Updated**: {os.path.basename(__file__)}\n")
        f.write(f"- **Total Rules Identified**: {total_rules}\n")
        f.write(f"- **Rules Referenced in Code**: {covered_count}\n")
        f.write(f"- **Rules Marked as Not Present**: {missing_count}\n")
        f.write(f"- **Coverage**: {covered_count/total_rules:.2%}\n\n")
        
        f.write("## Coverage Details\n\n")
        f.write("| Rule | References | Status |\n")
        f.write("| --- | --- | --- |\n")
        for rule in sorted_rules:
            count = covered_rules[rule]
            if rule in missing_rules:
                status = "⚠️ N/A"
            else:
                status = "✅" if count > 0 else "❌"
            f.write(f"| {rule} | {count} | {status} |\n")

    print(f"Audit complete. Results written to {output_file}")

if __name__ == "__main__":
    main()
