# -*- coding: utf-8 -*-
"""Centralized aliases for the ability parser.

This module contains mappings from human-readable pseudocode/Japanese text
to canonical engine types and default parameters.
"""

# Trigger type aliases (pseudocode -> canonical name)
TRIGGER_ALIASES = {
    "ON_YELL": "ON_REVEAL",
    "ON_YELL_SUCCESS": "ON_REVEAL",
    "ON_ACTIVATE": "ACTIVATED",
    "JIDOU": "ON_LEAVES",
    "ON_REVEAL": "ON_REVEAL",
    "ON_MEMBER_DISCARD": "ON_LEAVES",
    "ON_DISCARDED": "ON_LEAVES",
    "ON_REMOVE": "ON_LEAVES",
    "ON_SET": "ON_PLAY",
    "ON_STAGE_ENTRY": "ON_PLAY",
    "ON_PLAY_OTHER": "ON_PLAY",
    "ON_REVEAL_OTHER": "ON_REVEAL",
    "ON_LIVE_SUCCESS_OTHER": "ON_LIVE_SUCCESS",
    "ON_TURN_START": "TURN_START",
    "ON_TURN_END": "TURN_END",
    "ON_TAP": "ACTIVATED",
    "ON_REVEAL_SELF": "ON_REVEAL",
    "ON_LIVE_SUCCESS_SELF": "ON_LIVE_SUCCESS",
    "ACTIVATED_FROM_DISCARD": "ACTIVATED",
    "ON_ENERGY_CHARGE": "ACTIVATED",
    "ON_DRAW": "ACTIVATED",
    "ON_POSITION_CHANGE": "ON_LEAVES",
    "ON_MOVE": "ON_LEAVES",
    "ON_ABILITY_RESOLVE": "ON_ABILITY_RESOLVE",
    "ON_ABILITY_SUCCESS": "ON_ABILITY_SUCCESS",
}

# Effect type aliases (pseudocode -> canonical name)
EFFECT_ALIASES = {
    "TAP_PLAYER": "TAP_MEMBER",
    "CHARGE_ENERGY": "ENERGY_CHARGE",
    "MOVE_DISCARD": "MOVE_TO_DISCARD",
    "MOVE_HAND": "ADD_TO_HAND",
    "MOVE_TO_HAND": "ADD_TO_HAND",
    "ADD_HAND": "ADD_TO_HAND",
    "SELECT_LIMIT": "REDUCE_LIVE_SET_LIMIT",
    "POWER_UP": "BUFF_POWER",
    "REDUCE_SET_LIMIT": "REDUCE_LIVE_SET_LIMIT",
    "REDUCE_LIMIT": "REDUCE_LIVE_SET_LIMIT",
    "REDUCE_HEART": "REDUCE_HEART_REQ",
    "MOVE_DECK": "MOVE_TO_DECK",
    "SET_BASE_BLADES": "SET_BLADES",
    "GRANT_HEARTS": "ADD_HEARTS",
    "GRANT_HEART": "ADD_HEARTS",
    "CHANGE_BASE_HEART": "TRANSFORM_HEART",
    "SELECT_LIVE_CARD": "SELECT_LIVE",
    "POSITION_CHANGE": "MOVE_MEMBER",
    "INCREASE_HEART": "INCREASE_HEART_COST",
    "CHANGE_YELL_BLADE_COLOR": "TRANSFORM_COLOR",
    "TRANSFORM_YELL_BLADES": "TRANSFORM_COLOR",
    "OPPONENT_CHOICE": "OPPONENT_CHOOSE",
    "LOOK_AND_CHOOSE_ORDER": "ORDER_DECK",
    "LOOK_AND_CHOOSE_REVEAL": "LOOK_AND_CHOOSE",
    "SET_HEART_REQ": "SET_HEART_COST",
    "CYCLE_AREAS": "SWAP_AREA",
    "SELECT_OPTION": "SELECT_MODE",
    "CHOICE_MODE": "SELECT_MODE",
    "HALVE_VALUE": "DIV_VALUE",
    "REORDER_DISCARD": "LOOK_REORDER_DISCARD",
    "HEART_SELECT": "COLOR_SELECT",
    "FLAVOR": "FLAVOR_ACTION",
}

# Effect aliases that require additional param modifications
# Format: alias -> (canonical_name, params_dict)
EFFECT_ALIASES_WITH_PARAMS = {
    "CHARGE_SELF": ("ENERGY_CHARGE", {"target": "MEMBER_SELF"}),
    "PLACE_ENERGY_WAIT": ("ENERGY_CHARGE", {"wait": True}),
    "RECOVER_FROM_CHEER": ("RECOVER_MEMBER", {"source": "yell"}),
    "BOOST_SCORE_PER_COLOR": ("BOOST_SCORE", {"multiplier": "color"}),
    "LOOK_AND_CHOOSE_REVEAL": ("LOOK_AND_CHOOSE", {"reveal": True}),
    "REMOVE_SELF": ("MOVE_TO_DISCARD", {"target": "MEMBER_SELF"}),
    "SWAP_SELF": ("SWAP_ZONE", {"target": "MEMBER_SELF"}),
    "TRIGGER_YELL_AGAIN": ("META_RULE", {"meta_type": "TRIGGER_YELL_AGAIN"}),
    "DISCARD_HAND": ("MOVE_TO_DISCARD", {"source": "HAND", "destination": "discard"}),
    "RECOVER_LIVE": ("RECOVER_LIVE", {"source": "discard"}),
    "RECOVER_MEMBER": ("RECOVER_MEMBER", {"source": "discard"}),
    "SELECT_RECOVER_LIVE": ("RECOVER_LIVE", {"source": "discard"}),
    "SELECT_RECOVER_MEMBER": ("RECOVER_MEMBER", {"source": "discard"}),
    "DISCARD_UNTIL": ("MOVE_TO_DISCARD", {"operation": "UNTIL_SIZE"}),
    "YELL_MULLIGAN": ("META_RULE", {"meta_type": "ACTION_YELL_MULLIGAN"}),
}

# Condition type aliases (pseudocode -> canonical name)
# Format: alias -> (canonical_name, extra_params)
CONDITION_ALIASES = {
    "ONCE": ("TURN_1", {}),
    "TURN_1": ("TURN_1", {}),
    "ALL_MEMBERS": ("GROUP_FILTER", {"all": True}),
    "COUNT_LIVE": ("COUNT_LIVE_ZONE", {}),
    "HAS_SUCCESS_LIVE": ("COUNT_SUCCESS_LIVE", {}),
    "SUM_ENERGY": ("COUNT_ENERGY", {}),
    "BATON_FROM_NAME": ("BATON", {}),
    "MOVED_THIS_TURN": ("HAS_MOVED", {}),
    "DECK_REFRESHED_THIS_TURN": ("DECK_REFRESHED", {}),
    "HAND_SIZE_DIFF": ("OPPONENT_HAND_DIFF", {}),
    "BATON_TOUCH": ("BATON", {}),
    "BATON_COUNT": ("BATON", {}),
    "BATON": ("BATON", {}),
    "HAND_SIZE": ("COUNT_HAND", {}),
    "BLADES": ("COUNT_BLADES", {}),
    "TOTAL_BLADES": ("TOTAL_BLADES", {}),
    "HEART_LEAD": ("HEART_LEAD", {}),
    "OPPONENT_HAS_WAIT": ("OPPONENT_HAS_WAIT", {}),
    "IS_IN_DISCARD": ("IS_IN_DISCARD", {}),
    "COUNT_ENERGY_EXACT": ("COUNT_ENERGY_EXACT", {}),
    "ENERGY_COUNT": ("COUNT_ENERGY", {}),
    "COUNT_BLADE_HEART_TYPES": ("COUNT_BLADE_HEART_TYPES", {}),
    "OPPONENT_HAS_EXCESS_HEART": ("OPPONENT_HAS_EXCESS_HEART", {}),
    "SCORE_TOTAL": ("SCORE_TOTAL_CHECK", {}),
    "HAS_EXCESS_HEART": ("HAS_EXCESS_HEART", {}),
    "COUNT_MEMBER": ("COUNT_STAGE", {}),
    "TOTAL_HEARTS": ("COUNT_HEARTS", {}),
    "HEARTS_COUNT": ("COUNT_HEARTS", {}),
    "ALL_MEMBER": ("GROUP_FILTER", {}),
    "MEMBER_AT_SLOT": ("GROUP_FILTER", {}),
    "HAS_LIVE_HEART_COLORS": ("HAS_COLOR", {}),
    "COUNT_REVEALED": ("COUNT_HAND", {}),
    "COUNT_DISCARDED_THIS_TURN": ("COUNT_DISCARD", {}),
    "CHECK_GROUP_FILTER": ("GROUP_FILTER", {}),
    "FILTER": ("GROUP_FILTER", {}),
    "SELECT_YELL": ("GROUP_FILTER", {"zone": "yell"}),
    "NAME_MATCH": ("GROUP_FILTER", {"filter": "NAME_MATCH"}),
    "SUCCESS": ("MODAL_ANSWER", {}),
    "MATCH_PREVIOUS": ("MODAL_ANSWER", {}),
    "COST_LEAD": ("SCORE_COMPARE", {"type": "cost", "target": "opponent", "comparison": "GT"}),
    "SCORE_LEAD": ("SCORE_COMPARE", {"type": "score", "comparison": "GT", "target": "opponent"}),
    "TYPE_MEMBER": ("TYPE_CHECK", {"card_type": "member"}),
    "TYPE_LIVE": ("TYPE_CHECK", {"card_type": "live"}),
    "ENERGY_LAGGING": ("OPPONENT_ENERGY_DIFF", {"comparison": "GE", "diff": 1}),
    "ENERGY_LEAD": ("OPPONENT_ENERGY_DIFF", {"comparison": "LE", "diff": 0}),
    "SUM_SCORE": ("SCORE_COMPARE", {"type": "score", "comparison": "GE"}),
    "SUM_COST": ("SCORE_COMPARE", {"type": "cost", "comparison": "GE"}),
    "COST_LE_9": ("COST_CHECK", {"comparison": "LE", "value": 9}),
    "SCORE_EQUAL_OPPONENT": ("SCORE_COMPARE", {"comparison": "EQ", "target": "opponent"}),
    "SUCCESS_LIVE_COUNT_EQUAL_OPPONENT": ("SCORE_COMPARE", {"type": "score", "comparison": "EQ", "target": "opponent"}),
    "SCORE_TOTAL": ("SCORE_COMPARE", {"type": "score", "comparison": "GE"}),
    "COUNT_ACTIVATED": ("COUNT_STAGE", {"filter": "ACTIVATED"}),
    "HAS_REMAINING_HEART": ("COUNT_HEARTS", {"min": 1}),
    "COUNT_CHARGED_ENERGY": ("COUNT_ENERGY", {}),
    "SUM_SUCCESS_LIVE": ("COUNT_SUCCESS_LIVE", {}),
    "SUM_HEARTS": ("COUNT_HEARTS", {}),
    "EXTRA_HEARTS": ("COUNT_HEARTS", {"min": 1}),
    "HAS_ACTIVE_ENERGY": ("COUNT_ENERGY", {"filter": "active", "min": 1}),
    "ALL_ENERGY_ACTIVE": ("COUNT_ENERGY", {"filter": "active", "comparison": "ALL"}),
    "ENERGY": ("COUNT_ENERGY", {}),
    "HAS_TYPE_LIVE": ("TYPE_CHECK", {"card_type": "live"}),
    "NOT_MOVED_THIS_TURN": ("HAS_MOVED", {}),  # negated handled separately
    # COUNT_CARDS for unique member checks across zones
    "COUNT_CARDS": ("GROUP_FILTER", {}),
    "COUNT_UNIQUE_MEMBERS": ("GROUP_FILTER", {"unique": True}),
    "MAIN_PHASE": ("MAIN_PHASE", {}),
    "SELECT_MEMBER": ("SELECT_MEMBER", {}),
    "SUCCESS_PILE_COUNT": ("SUCCESS_PILE_COUNT", {}),
    "IS_SELF_MOVE": ("IS_SELF_MOVE", {}),
    "DISCARDED_CARDS": ("DISCARDED_CARDS", {}),
    "YELL_REVEALED_UNIQUE_COLORS": ("YELL_REVEALED_UNIQUE_COLORS", {}),
    "SYNC_COST": ("SYNC_COST", {}),
    "SUM_VALUE": ("SUM_VALUE", {}),
    "VALUE_EQ": ("SUM_VALUE", {}),
    "IS_WAIT": ("IS_WAIT", {}),
    "ON_ABILITY_RESOLVE": ("ON_ABILITY_RESOLVE", {}),
    "TARGET_MEMBER_HAS_NO_HEARTS": ("TARGET_MEMBER_HAS_NO_HEARTS", {}),
}

# Conditions that map to HAS_KEYWORD with a keyword param
KEYWORD_CONDITIONS = {
    "COUNT_PLAYED_THIS_TURN": "PLAYED_THIS_TURN",
    "REVEALED_CONTAINS": "REVEALED_CONTAINS",
    "ZONE": "ZONE_CHECK",
    "AREA": "AREA_CHECK",
    "EFFECT_NEGATED_THIS_TURN": "EFFECT_NEGATED",
    "HIGHEST_COST_ON_STAGE": "HIGHEST_COST",
    "COUNT_UNIQUE_NAMES": "UNIQUE_NAMES",
    "OPPONENT_EXTRA_HEARTS": "OPPONENT_EXTRA_HEARTS",
    "HAS_LIVE_SET": "HAS_LIVE_SET",
    "SUCCESS_LIVES_CONTAINS": "SUCCESS_LIVES_CONTAINS",
    "YELL_COUNT": "YELL_COUNT",
    "COUNT_YELL_REVEALED": "YELL_COUNT",
}

# Conditions that should be ignored (map to NONE)
IGNORED_CONDITIONS = {
    "TARGET",
    "ON_YELL",
    "ON_YELL_SUCCESS",
}

# Maximum value for "ALL" selector
MAX_SELECT_ALL = 99
