import json

with open('../data/ability_frame_source.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

abilities = data['abilities']
reverted = 0

# Revert frame_verification for abilities that were marked verified by the script
# The script added notes like "Pay 1 energy, if energy >= 9, look at 5 cards..."
# We'll revert any that have these automated-looking notes

for i, ability in enumerate(abilities):
    frame_verification = ability.get('frame_verification', {})
    if frame_verification.get('verified', False):
        notes = frame_verification.get('notes', [])
        # Check if notes look like they were generated by the script
        auto_generated = False
        for note in notes:
            if 'cards share this pattern' in note:
                auto_generated = True
                break
            if 'Frame 0: COUNT_ENERGY' in note and 'Frame 6: LOOK_AND_CHOOSE' in note:
                auto_generated = True
                break
        
        if auto_generated:
            # Revert to unverified state
            ability['frame_verification']['verified'] = False
            ability['frame_verification']['issues'] = [
                "Verification needed - frames need manual review"
            ]
            if 'notes' in ability['frame_verification']:
                del ability['frame_verification']['notes']
            if 'text_mapping' in ability['frame_verification']:
                del ability['frame_verification']['text_mapping']
            if 'required_frames' in ability['frame_verification']:
                del ability['frame_verification']['required_frames']
            reverted += 1

# Also revert frame data changes that were made by the script
# The script added: reveal=1, group_id=MUSE, dest_discard=1, remainder_zone=DISCARD, char_id_1 filters
# We need to identify which frames were modified and revert them

# For now, let's just revert the group_id=MUSE changes since those are easy to identify
for i, ability in enumerate(abilities):
    frames = ability.get('frames', [])
    for frame in frames:
        if frame['op'] == 'LOOK_AND_CHOOSE':
            if 'attr' in frame and frame['attr'].get('group_id') == 'MUSE':
                # Revert the group_id change
                del frame['attr']['group_id']
                if not frame['attr']:
                    del frame['attr']
                reverted += 1

# Write back
with open('../data/ability_frame_source.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Reverted {reverted} automated verification changes")
