from enum import IntEnum

from .generated_metadata import OPCODES


class Opcode(IntEnum):
    """
    Unified Opcode definitions for the LovecaSim engine.
    @generated by tools/sync_metadata.py (via generated_metadata.py)
    """

    pass


# Dynamically populate Opcode enum from generated metadata
from .generated_metadata import CONDITIONS, COSTS

for name, value in OPCODES.items():
    setattr(Opcode, name, value)

# Conditions are typically used as Opcodes with CHECK_ prefix in the bytecode
for name, value in CONDITIONS.items():
    setattr(Opcode, f"CHECK_{name}", value)

# Some costs are also used as Opcodes directly or via prefix
for name, value in COSTS.items():
    setattr(Opcode, f"COST_{name}", value)
