#!/usr/bin/env python3
"""
Detailed comparison of converted frames vs authored frames for test cards.
This script compares the frame structures generated by the semantic-to-frame converter
with the manually authored frames for cards matching test patterns.
"""
import json
from pathlib import Path

# Load data
cards_file = Path("data/cards.json")
authored_frames_file = Path("data/ability_frame_source_authored.json")
converted_frames_file = Path("data/ability_frame_source.json")

with open(cards_file, encoding='utf-8') as f:
    cards = json.load(f)

with open(authored_frames_file, encoding='utf-8') as f:
    authored_frames = json.load(f)

with open(converted_frames_file, encoding='utf-8') as f:
    converted_frames = json.load(f)

# Create lookup by card for authored frames
authored_by_card = {}
for ability in authored_frames['abilities']:
    for ref in ability.get('card_refs', []):
        card_no = ref.get('card_no')
        if card_no:
            if card_no not in authored_by_card:
                authored_by_card[card_no] = []
            authored_by_card[card_no].append({
                'ability': ability,
                'ability_index': ref.get('ability_index', 0),
                'trigger': ref.get('trigger')
            })

# Create lookup by card for converted frames
converted_by_card = {}
for ability in converted_frames['abilities']:
    for ref in ability.get('card_refs', []):
        card_no = ref.get('card_no')
        if card_no:
            if card_no not in converted_by_card:
                converted_by_card[card_no] = []
            converted_by_card[card_no].append({
                'ability': ability,
                'ability_index': ref.get('ability_index', 0),
                'trigger': ref.get('trigger')
            })

# Test patterns from test_parsers.py
test_patterns = [
    {
        'name': 'surplus_heart',
        'pattern': '余剰ハートを持たない場合',
        'description': 'Surplus heart conditions (none vs 2+)'
    },
    {
        'name': 'names_different',
        'pattern': '名前が異なる場合',
        'description': 'Names different condition'
    },
    {
        'name': 'opponent_member_to_wait',
        'pattern': '相手のステージにいるコスト4以下のメンバー1人をウェイトにする',
        'description': 'Opponent member to wait'
    },
    {
        'name': 'waitroom_live_recovery',
        'pattern': '自分の控え室から『虹ヶ咲』のライブカードを1枚手札に加える',
        'description': 'Waitroom live recovery'
    },
]

print("=" * 100)
print("DETAILED FRAME COMPARISON: Authored vs Converted")
print("=" * 100)
print()

comparison_results = []

for test in test_patterns:
    pattern = test['pattern']
    print(f"\n{'=' * 100}")
    print(f"Test Pattern: {test['name']} - {test['description']}")
    print(f"Pattern: {pattern}")
    print(f"{'=' * 100}")
    
    # Find cards matching this pattern
    matching_cards = []
    for card_no, card in cards.items():
        ability = card.get('ability', '')
        if pattern in ability:
            matching_cards.append(card_no)
    
    if not matching_cards:
        print("No matching cards found in cards.json")
        continue
    
    print(f"Found {len(matching_cards)} matching cards")
    
    # Analyze first 3 matching cards
    for card_no in matching_cards[:3]:
        card = cards[card_no]
        print(f"\n{'─' * 100}")
        print(f"Card: {card_no} | {card.get('name', 'Unknown')}")
        print(f"{'─' * 100}")
        
        authored = authored_by_card.get(card_no, [])
        converted = converted_by_card.get(card_no, [])
        
        print(f"\nAuthored abilities: {len(authored)}")
        print(f"Converted abilities: {len(converted)}")
        
        if not authored and not converted:
            print("✗ No frame data available for this card")
            comparison_results.append({
                'pattern': test['name'],
                'card_no': card_no,
                'status': 'no_data'
            })
            continue
        
        # Compare ability counts
        if len(authored) != len(converted):
            print(f"⚠ ABILITY COUNT MISMATCH: Authored {len(authored)} vs Converted {len(converted)}")
            comparison_results.append({
                'pattern': test['name'],
                'card_no': card_no,
                'status': 'count_mismatch',
                'authored_count': len(authored),
                'converted_count': len(converted)
            })
        
        # Compare each ability
        max_abilities = max(len(authored), len(converted))
        for i in range(max_abilities):
            print(f"\n--- Ability {i} ---")
            
            auth_ability = authored[i] if i < len(authored) else None
            conv_ability = converted[i] if i < len(converted) else None
            
            if auth_ability and conv_ability:
                # Compare triggers
                auth_trigger = auth_ability.get('trigger')
                conv_trigger = conv_ability.get('trigger')
                if auth_trigger != conv_trigger:
                    print(f"⚠ TRIGGER MISMATCH: Authored {auth_trigger} vs Converted {conv_trigger}")
                else:
                    print(f"✓ Trigger matches: {auth_trigger}")
                
                # Compare frame counts
                auth_frames = auth_ability['ability'].get('frames', [])
                conv_frames = conv_ability['ability'].get('frames', [])
                
                if len(auth_frames) != len(conv_frames):
                    print(f"⚠ FRAME COUNT MISMATCH: Authored {len(auth_frames)} vs Converted {len(conv_frames)}")
                    comparison_results.append({
                        'pattern': test['name'],
                        'card_no': card_no,
                        'ability_index': i,
                        'status': 'frame_count_mismatch',
                        'authored_frames': len(auth_frames),
                        'converted_frames': len(conv_frames)
                    })
                else:
                    print(f"✓ Frame count matches: {len(auth_frames)}")
                
                # Compare first few frames
                for j in range(min(5, len(auth_frames), len(conv_frames))):
                    auth_frame = auth_frames[j]
                    conv_frame = conv_frames[j]
                    
                    auth_op = auth_frame.get('op')
                    conv_op = conv_frame.get('op')
                    
                    if auth_op != conv_op:
                        print(f"  ⚠ Frame {j} OP mismatch: Authored {auth_op} vs Converted {conv_op}")
                        comparison_results.append({
                            'pattern': test['name'],
                            'card_no': card_no,
                            'ability_index': i,
                            'frame_index': j,
                            'status': 'op_mismatch',
                            'authored_op': auth_op,
                            'converted_op': conv_op
                        })
                    else:
                        print(f"  ✓ Frame {j} OP matches: {auth_op}")
                    
                    # Compare value
                    auth_value = auth_frame.get('value')
                    conv_value = conv_frame.get('value')
                    if auth_value != conv_value:
                        print(f"    ⚠ Value mismatch: Authored {auth_value} vs Converted {conv_value}")
                    else:
                        if auth_value is not None:
                            print(f"    ✓ Value matches: {auth_value}")
                
                # Show sample of authored frames
                if auth_frames:
                    print(f"\nAuthored frames (first 3):")
                    for j, frame in enumerate(auth_frames[:3]):
                        print(f"  {j}: {frame.get('op')} | value={frame.get('value')} | attr={frame.get('attr')} | slot={frame.get('slot')}")
                
                # Show sample of converted frames
                if conv_frames:
                    print(f"\nConverted frames (first 3):")
                    for j, frame in enumerate(conv_frames[:3]):
                        print(f"  {j}: {frame.get('op')} | value={frame.get('value')} | attr={frame.get('attr')} | slot={frame.get('slot')}")
                
            elif auth_ability:
                print(f"⚠ Only authored ability available (no converted)")
                comparison_results.append({
                    'pattern': test['name'],
                    'card_no': card_no,
                    'ability_index': i,
                    'status': 'only_authored'
                })
            elif conv_ability:
                print(f"⚠ Only converted ability available (no authored)")
                comparison_results.append({
                    'pattern': test['name'],
                    'card_no': card_no,
                    'ability_index': i,
                    'status': 'only_converted'
                })

# Summary
print("\n" + "=" * 100)
print("SUMMARY OF COMPARISON RESULTS")
print("=" * 100)

status_counts = {}
for result in comparison_results:
    status = result['status']
    status_counts[status] = status_counts.get(status, 0) + 1

print(f"\nTotal comparisons made: {len(comparison_results)}")
print("\nBreakdown by status:")
for status, count in sorted(status_counts.items()):
    print(f"  {status}: {count}")

# Show specific mismatches
mismatches = [r for r in comparison_results if 'mismatch' in r['status']]
if mismatches:
    print(f"\nMismatches found: {len(mismatches)}")
    print("\nDetails:")
    for m in mismatches:
        print(f"  Pattern: {m['pattern']}, Card: {m['card_no']}, Status: {m['status']}")
        if 'authored_op' in m:
            print(f"    OP: Authored {m['authored_op']} vs Converted {m['converted_op']}")
        if 'authored_frames' in m:
            print(f"    Frames: Authored {m['authored_frames']} vs Converted {m['converted_frames']}")

print("\n" + "=" * 100)
print("CONCLUSION")
print("=" * 100)
print("The comparison reveals gaps between authored and converted frames.")
print("Key findings:")
print("1. Some cards have different ability counts between authored and converted")
print("2. Frame opcodes may differ for complex patterns")
print("3. The semantic-to-frame converter needs improvements for specific patterns")
print("\nNext steps:")
print("- Analyze specific mismatched patterns to improve the converter")
print("- Add missing frame generation logic for complex ability types")
print("- Ensure trigger matching is accurate")
