import datetime
import json
import os
from pathlib import Path

OPCODES = {
    "DRAW": "draw_cards({p}, {v} as u32);",
    "ADD_BLADES": "players[{p}].blade_buffs[{s}] += {v};",
    "ADD_HEARTS": "players[{p}].heart_buffs[{s}].add_to_color({a} as usize, {v} as i32);",
    "REDUCE_COST": "players[{p}].cost_reduction += {v};",
    "BOOST_SCORE": "players[{p}].live_score_bonus += {v};",
    "BUFF": "players[{p}].blade_buffs[{s}] += {v};",
    "ENERGY_CHARGE": "draw_energy_cards({p}, {v});",
    "SET_SCORE": "players[{p}].score = {v} as u32;",
    "TRANSFORM_COLOR": "players[{p}].color_transforms.push(({a} as u8, {s} as u8));",
    "ACTIVATE_MEMBER": "set_member_tapped({p}, {s}, false);",
    "MODIFY_SCORE_RULE": "players[{p}].live_score_bonus += {v};",
    "SET_TAPPED": "set_member_tapped({p}, {s}, true);",
    "PAY_ENERGY": "pay_energy({p}, {v});",
    "ACTIVATE_ENERGY": "activate_energy({p}, {v});",
}

ROOT_DIR = Path(__file__).resolve().parents[1]
DB_PATH = ROOT_DIR / "data" / "ability_frame_index.json"
OUT_PATH = ROOT_DIR / "engine_rust_src" / "src" / "core" / "hardcoded.rs"


def generate_rust(*, quiet: bool = False) -> bool:
    db_path = DB_PATH
    out_path = OUT_PATH

    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)

    out = []
    out.append(f"// @generated by tools/codegen_abilities.py on {datetime.datetime.now().isoformat()}")
    out.append("// GENERATED CODE - DO NOT EDIT")
    out.append("use crate::core::logic::{GameState, CardDatabase, AbilityContext};")
    out.append("")
    out.append(
        "pub fn execute_hardcoded_ability(state: &mut GameState, _db: &CardDatabase, card_id: i32, ab_idx: usize, ctx: &AbilityContext) -> bool {"
    )
    out.append("    let p_idx = ctx.player_id as usize;")
    out.append("    match (card_id, ab_idx) {")

    count = 0
    for entry in db.get("abilities", []):
        card_refs = entry.get("card_refs", [])
        frames = entry.get("frames", [])
        if not card_refs or not frames:
            continue

        # Keep the generator conservative. Anything with control flow or
        # non-trivial semantic frames should fall back to the interpreter.
        complex_ops = {
            "JUMP",
            "JUMP_IF_FALSE",
            "LOOK_AND_CHOOSE",
            "SELECT_MODE",
            "COLOR_SELECT",
            "ORDER_DECK",
            "MOVE_TO_DECK",
            "MOVE_TO_DISCARD",
            "PLAY_MEMBER_FROM_HAND",
            "HAS_KEYWORD",
            "GROUP_FILTER",
            "COUNT_STAGE",
            "COUNT_CARDS",
            "SUM_VALUE",
            "META_RULE",
        }

        simple_frames = []
        valid = True
        for frame in frames:
            op = str(frame.get("op") or frame.get("opcode") or frame.get("opcode_name") or frame.get("kind") or "").upper()
            if not op or op == "RETURN":
                continue
            if op in complex_ops:
                valid = False
                break
            if op not in OPCODES:
                valid = False
                break
            if bool(frame.get("negated") or frame.get("is_negated")):
                valid = False
                break

            slot = frame.get("slot", {})
            target_slot = slot.get("target_slot") if isinstance(slot, dict) else None
            if target_slot not in (0, 1, 2, 3, 4, 10):
                valid = False
                break

            simple_frames.append(frame)

        if valid and simple_frames:
            rust_lines = []
            for frame in simple_frames:
                op = str(frame.get("op")).upper()
                value = frame.get("value", 0)
                if not isinstance(value, int):
                    value = 0
                attr = frame.get("attr", {})
                if isinstance(attr, int):
                    a = attr
                elif isinstance(attr, dict):
                    a = int(attr.get("heart_color", attr.get("color", attr.get("color_index", attr.get("attr", 0)))))
                else:
                    a = 0
                slot = frame.get("slot", {})
                target_slot = slot.get("target_slot") if isinstance(slot, dict) else 0
                slot_expr = "ctx.target_slot as usize" if target_slot == 10 else f"{int(target_slot)} as usize"
                line = OPCODES[op].format(p="p_idx", v=value, a=a, s=slot_expr)
                rust_lines.append(line)

            if rust_lines:
                pseudo = " ".join((entry.get("pseudocode") or "").strip().splitlines())
                for card_ref in card_refs:
                    if not isinstance(card_ref, dict):
                        continue
                    card_id = card_ref.get("card_id")
                    ability_index = card_ref.get("ability_index")
                    if not isinstance(card_id, int) or not isinstance(ability_index, int):
                        continue

                    out.append(f"        ({card_id}, {ability_index}) => {{")
                    if pseudo:
                        out.append(f"            // pseudocode: {pseudo}")
                    for line in rust_lines:
                        out.append(f"            state.{line.strip()}")
                    out.append("            true")
                    out.append("        },")
                    count += 1

    out.append("        _ => false,")
    out.append("    }")
    out.append("}")

    content = "\n".join(out)
    changed = True
    if out_path.exists():
        with open(out_path, "r", encoding="utf-8") as f:
            changed = f.read() != content

    if changed:
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)

    if not quiet:
        if changed:
            print(f"Generated hardcoded logic for {count} abilities.")
        else:
            print(f"Hardcoded logic already up to date for {count} abilities.")
    return changed


if __name__ == "__main__":
    generate_rust()
