import glob
import json
import os
import sys

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from pr_server import init_game, optimize_history


def optimize_file(filepath):
    print(f"Optimizing {filepath}...")

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    history = data.get("states", [])
    if not history:
        print("Error: No states found in replay.")
        return

    # Use Level 3 Optimization (Action Log)
    init_game(deck_type="normal")  # Ensure DB and Seed initialized

    # We need to spoof the context since we are loading from file, not live memory.
    # CRITICAL LIMITATION: Standard replays DO NOT have the seed stored in them currently.
    # So we can only convert to Level 2 (DB-backed) from existing files.
    # BUT, the user wants "further optimization".
    # We can only do Level 3 if the source replay HAS the seed/decks/actions.
    # Standard replays DO have 'states', but extracting actions from states is hard (needs diffing).
    # However, for NEW replays (generated by pr_server from now on), we can do it.

    # Let's see if the file has 'seed' in it (if we updated save_replay correctly).
    seed = data.get("seed")
    action_log = data.get("action_log")  # Standard replays don't have this top-level, but check anyway.

    # If not present, we fall back to Level 2.
    if seed is None:
        print("Notice: No seed found in replay. Defaulting to Level 2 Optimization (DB-Backed).")
        optimized_data = optimize_history(history, exclude_db_cards=True)
    else:
        print(f"Level 3 Candidate: Seed={seed}")
        # We need action log. If it's not in file, we can't do Level 3.
        # So manual_optimize_replay ONLY upgrades Level 1 -> Level 2.
        # Level 3 is only possible for replays created AFTER this update.
        optimized_data = optimize_history(history, exclude_db_cards=True)

    # Structure output
    final_opt = {
        "game_id": data.get("game_id", 0),
        "timestamp": data.get("timestamp", ""),
        "winner": data.get("winner", -1),
        "input_file": os.path.basename(filepath),
        "registry": optimized_data["registry"],
        "states": optimized_data["states"],
    }

    output_path = filepath.replace(".json", "_opt.json")
    if output_path == filepath:
        output_path = filepath.replace(".json", "_reopt.json")

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(final_opt, f, ensure_ascii=False, indent=2)

    size_std = os.path.getsize(filepath)
    size_opt = os.path.getsize(output_path)
    savings = (1 - size_opt / size_std) * 100

    print(f"Original: {size_std / 1024:.2f} KB")
    print(f"Optimized: {size_opt / 1024:.2f} KB")
    print(f"Reduction: {savings:.2f}%")
    print("-" * 30)


def scan_and_optimize():
    # Find largest non-optimized replay
    files = glob.glob("replays/*.json")
    targets = [f for f in files if "_opt" not in f and "replay_" in f or "large_" in f]

    if not targets:
        print("No replay files found.")
        return

    # Sort by size descending
    targets.sort(key=lambda x: os.path.getsize(x), reverse=True)

    print(f"Found {len(targets)} replay files.")

    # Optimize the largest one
    largest = targets[0]
    print(f"Selecting largest file: {largest}")
    optimize_file(largest)


if __name__ == "__main__":
    scan_and_optimize()
