import json
import os
import re

def to_pascal_case(snake_str):
    if not snake_str:
        return ""
    # Handle acronyms or special cases if any
    parts = snake_str.lower().split('_')
    return ''.join(x.capitalize() for x in parts)

def sync():
    metadata_path = "data/metadata.json"
    if not os.path.exists(metadata_path):
        print(f"Error: {metadata_path} not found")
        return

    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    # --- Generate Rust Constants (Generated Constants file) ---
    # This file remains for i32 constant access (direct bytecode usage)
    rust_const_path = "engine_rust_src/src/core/generated_constants.rs"
    with open(rust_const_path, "w", encoding="utf-8") as f:
        f.write("//! @generated by tools/sync_metadata.py\n")
        f.write("#![allow(dead_code)]\n\n")
        
        f.write("// Opcodes\n")
        for key, val in metadata["opcodes"].items():
            f.write(f"pub const O_{key}: i32 = {val};\n")
        
        f.write("\n// Action ID Bases\n")
        for key, val in metadata["action_bases"].items():
            f.write(f"pub const ACTION_BASE_{key}: i32 = {val};\n")

        f.write("\n// Condition Types\n")
        for key, val in metadata["conditions"].items():
            f.write(f"pub const C_{key}: i32 = {val};\n")

        f.write("\n// Cost Types\n")
        for key, val in metadata["costs"].items():
            f.write(f"pub const COST_{key}: i32 = {val};\n")

        f.write("\n// Extra Constants\n")
        for key, val in metadata.get("extra_constants", {}).items():
            const_type = "i32"
            if key.startswith("FLAG_"):
                const_type = "u64"
            elif key.startswith("CHOICE_FLAG_"):
                const_type = "u8"
            elif key.startswith("SYN_FLAG_") or key.startswith("COST_FLAG_"):
                const_type = "u32"
            f.write(f"pub const {key}: {const_type} = {val};\n")

    # --- Generate Rust Enums (FULL OVERWRITE of enums.rs) ---
    rust_enum_path = "engine_rust_src/src/core/enums.rs"
    with open(rust_enum_path, "w", encoding="utf-8") as f:
        f.write("//! @generated by tools/sync_metadata.py\n")
        f.write("#![allow(unused_imports)]\n")
        f.write("use serde::{Deserialize, Serialize};\n")
        f.write("use serde_repr::{Deserialize_repr, Serialize_repr};\n")
        f.write("pub use crate::core::generated_constants::*;\n\n")

        # TriggerType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum TriggerType {\n")
        f.write("    #[default]\n")
        for key, val in metadata["triggers"].items():
            variant = to_pascal_case(key) if key != "NONE" else "None"
            f.write(f"    {variant} = {val},\n")
        f.write("}\n\n")

        # TargetType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum TargetType {\n")
        f.write("    #[default]\n")
        for key, val in metadata["targets"].items():
            variant = to_pascal_case(key) if key != "SELF" else "Self_" # 'Self' is reserved
            f.write(f"    {variant} = {val},\n")
        f.write("}\n\n")

        # EffectType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum EffectType {\n")
        f.write("    #[default]\n")
        # We need a default. Usually NOP=0, but EffectType start at 10. 
        # Let's use first one or NOP if exists.
        if "NOP" in metadata["opcodes"]:
             f.write("    Nop = 0,\n")
        else:
             # Fallback to a safe default if Nop is missing
             first_op = list(metadata["opcodes"].keys())[0]
             f.write(f"    {to_pascal_case(first_op)} = {metadata['opcodes'][first_op]},\n")

        for key, val in metadata["opcodes"].items():
            if key == "NOP": continue
            f.write(f"    {to_pascal_case(key)} = {val},\n")
        f.write("}\n\n")

        # ConditionType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum ConditionType {\n")
        f.write("    #[default]\n")
        f.write("    None = 0,\n")
        for key, val in metadata["conditions"].items():
            f.write(f"    {to_pascal_case(key)} = {val},\n")
        f.write("}\n\n")

        # AbilityCostType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum AbilityCostType {\n")
        f.write("    #[default]\n")
        f.write("    None = 0,\n")
        for key, val in metadata["costs"].items():
            if key == "NONE": continue
            f.write(f"    {to_pascal_case(key)} = {val},\n")
        f.write("}\n\n")

        # Phase
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(i8)]\n")
        f.write("pub enum Phase {\n")
        f.write("    #[default]\n")
        # Phases are tricky because they include negative values.
        # Sorted by value
        sorted_phases = sorted(metadata["phases"].items(), key=lambda x: x[1])
        for key, val in sorted_phases:
            f.write(f"    {to_pascal_case(key)} = {val},\n")
        f.write("}\n")

    # --- Generate JS Constants ---
    js_path = "frontend/web_ui/js/generated_constants.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("/** @generated by tools/sync_metadata.py */\n\n")
        f.write("export const Opcodes = {\n")
        for key, val in metadata["opcodes"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")
        
        f.write("export const TriggerType = {\n")
        for key, val in metadata["triggers"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const TargetType = {\n")
        for key, val in metadata["targets"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const ActionBases = {\n")
        for key, val in metadata["action_bases"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")
        
        f.write("export const Phases = {\n")
        for key, val in metadata["phases"].items():
            f.write(f"    {key}: {val},\n")
            f.write(f"    \"{val}\": \"{key}\",\n")
        f.write("};\n\n")

        f.write("export const ConditionTypes = {\n")
        for key, val in metadata["conditions"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const CostTypes = {\n")
        for key, val in metadata["costs"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const ExtraConstants = {\n")
        for key, val in metadata.get("extra_constants", {}).items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n")

    # --- Generate Python Metadata ---
    py_path = "engine/models/generated_metadata.py"
    with open(py_path, "w", encoding="utf-8") as f:
        f.write("# @generated by tools/sync_metadata.py\n\n")
        
        sections = [
            ("OPCODES", "opcodes"),
            ("TRIGGERS", "triggers"),
            ("TARGETS", "targets"),
            ("ACTION_BASES", "action_bases"),
            ("CONDITIONS", "conditions"),
            ("COSTS", "costs"),
            ("PHASES", "phases"),
            ("EXTRA_CONSTANTS", "extra_constants")
        ]
        
        for var_name, meta_key in sections:
            f.write(f"{var_name} = {{\n")
            for key, val in metadata.get(meta_key, {}).items():
                if isinstance(key, str):
                    f.write(f"    \"{key}\": {val},\n")
                else:
                    f.write(f"    {key}: {val},\n")
            f.write("}\n\n")

    print("Successfully synchronized metadata to Rust, JS, and Python!")

if __name__ == "__main__":
    sync()

