import json
import os


def to_pascal_case(snake_str):
    if not snake_str:
        return ""
    # Handle acronyms or special cases if any
    parts = snake_str.lower().split("_")
    return "".join(x.capitalize() for x in parts)


def sync():
    metadata_path = "data/metadata.json"
    if not os.path.exists(metadata_path):
        print(f"Error: {metadata_path} not found")
        return

    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    unused_list = metadata.get("unused", [])

    # --- Generate Rust Constants (Generated Constants file) ---
    # This file remains for i32 constant access (direct bytecode usage)
    rust_const_path = "engine_rust_src/src/core/generated_constants.rs"
    with open(rust_const_path, "w", encoding="utf-8") as f:
        f.write("//! @generated by tools/sync_metadata.py\n")
        f.write("#![allow(dead_code)]\n\n")

        f.write("// Opcodes\n")
        for key, val in metadata["opcodes"].items():
            comment = " // [UNUSED]" if key in unused_list else ""
            f.write(f"pub const O_{key}: i32 = {val};{comment}\n")

        f.write("\n// Action ID Bases\n")
        for key, val in metadata["action_bases"].items():
            f.write(f"pub const ACTION_BASE_{key}: i32 = {val};\n")

        f.write("\n// Condition Types\n")
        for key, val in metadata["conditions"].items():
            comment = " // [UNUSED]" if key in unused_list else ""
            f.write(f"pub const C_{key}: i32 = {val};{comment}\n")

        f.write("\n// Cost Types\n")
        for key, val in metadata["costs"].items():
            f.write(f"pub const COST_{key}: i32 = {val};\n")

        f.write("\n// Choice Types\n")
        for key, val in metadata.get("choices", {}).items():
            f.write(f"pub const CHOICE_{key}: i32 = {val};\n")

        f.write("\n// Extra Constants\n")
        for key, val in metadata.get("extra_constants", {}).items():
            const_type = "i32"
            if key.startswith("FLAG_") or key.startswith("FILTER_") or key.startswith("KEYWORD_"):
                const_type = "u64"
            elif key.startswith("CHOICE_FLAG_"):
                const_type = "u8"
            elif key.startswith("SYN_FLAG_") or key.startswith("COST_FLAG_"):
                const_type = "u32"

            # Write with literal suffix for u64/u32 to avoid warnings/errors
            suffix = "u64" if const_type == "u64" else "u32" if const_type == "u32" else ""
            f.write(f"pub const {key}: {const_type} = {val}{suffix};\n")

    # --- Generate Rust Enums (FULL OVERWRITE of enums.rs) ---
    rust_enum_path = "engine_rust_src/src/core/enums.rs"
    with open(rust_enum_path, "w", encoding="utf-8") as f:
        f.write("//! @generated by tools/sync_metadata.py\n")
        f.write("#![allow(unused_imports)]\n")
        f.write("use serde::{Deserialize, Serialize};\n")
        f.write("use serde_repr::{Deserialize_repr, Serialize_repr};\n")
        f.write("pub use crate::core::generated_constants::*;\n\n")

        # TriggerType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum TriggerType {\n")
        f.write("    #[default]\n")
        for key, val in metadata["triggers"].items():
            variant = to_pascal_case(key) if key != "NONE" else "None"
            comment = " /// [UNUSED]" if key in unused_list else ""
            f.write(f"    {variant} = {val},{comment}\n")
        f.write("}\n\n")

        # TargetType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum TargetType {\n")
        f.write("    #[default]\n")
        for key, val in metadata["targets"].items():
            variant = to_pascal_case(key) if key != "SELF" else "Self_"  # 'Self' is reserved
            f.write(f"    {variant} = {val},\n")
        f.write("}\n\n")

        # EffectType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum EffectType {\n")
        f.write("    #[default]\n")
        # We need a default. Usually NOP=0, but EffectType start at 10.
        # Let's use first one or NOP if exists.
        if "NOP" in metadata["opcodes"]:
            f.write("    Nop = 0,\n")
        else:
            # Fallback to a safe default if Nop is missing
            first_op = list(metadata["opcodes"].keys())[0]
            f.write(f"    {to_pascal_case(first_op)} = {metadata['opcodes'][first_op]},\n")

        for key, val in metadata["opcodes"].items():
            if key == "NOP":
                continue
            comment = " /// [UNUSED]" if key in unused_list else ""
            f.write(f"    {to_pascal_case(key)} = {val},{comment}\n")
        f.write("}\n\n")

        # ConditionType
        # Check if any condition values exceed u8 range
        max_condition_val = max(metadata["conditions"].values()) if metadata["conditions"] else 0
        condition_repr = "u16" if max_condition_val > 255 else "u8"
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write(f"#[repr({condition_repr})]\n")
        f.write("pub enum ConditionType {\n")
        f.write("    #[default]\n")
        f.write("    None = 0,\n")
        for key, val in metadata["conditions"].items():
            comment = " /// [UNUSED]" if key in unused_list else ""
            f.write(f"    {to_pascal_case(key)} = {val},{comment}\n")
        f.write("}\n\n")

        # AbilityCostType
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(u8)]\n")
        f.write("pub enum AbilityCostType {\n")
        f.write("    #[default]\n")
        f.write("    None = 0,\n")
        for key, val in metadata["costs"].items():
            if key == "NONE":
                continue
            f.write(f"    {to_pascal_case(key)} = {val},\n")
        f.write("}\n\n")

        # ChoiceType
        if "choices" in metadata:
            f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
            f.write("#[repr(u8)]\n")
            f.write("pub enum ChoiceType {\n")
            f.write("    #[default]\n")
            f.write("    None = 0,\n")
            for key, val in metadata["choices"].items():
                if key == "NONE":
                    continue
                f.write(f"    {to_pascal_case(key)} = {val},\n")
            f.write("}\n\n")

            f.write("impl ChoiceType {\n")
            f.write("    pub fn from_str(s: &str) -> Self {\n")
            f.write("        match s {\n")
            for key, val in metadata["choices"].items():
                if key == "NONE": continue
                f.write(f'            "{key}" => ChoiceType::{to_pascal_case(key)},\n')
            f.write("            _ => ChoiceType::None,\n")
            f.write("        }\n")
            f.write("    }\n")
            f.write("    pub fn as_str(&self) -> &'static str {\n")
            f.write("        match self {\n")
            for key, val in metadata["choices"].items():
                if key == "NONE": continue
                f.write(f'            ChoiceType::{to_pascal_case(key)} => "{key}",\n')
            f.write('            ChoiceType::None => "NONE",\n')
            f.write("        }\n")
            f.write("    }\n")
            f.write("}\n\n")
            f.write("impl std::fmt::Display for ChoiceType {\n")
            f.write("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n")
            f.write('        write!(f, "{}", self.as_str())\n')
            f.write("    }\n")
            f.write("}\n\n")

        # Phase
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr, Default)]\n")
        f.write("#[repr(i8)]\n")
        f.write("pub enum Phase {\n")
        f.write("    #[default]\n")
        # Phases are tricky because they include negative values.
        # Sorted by value
        sorted_phases = sorted(metadata["phases"].items(), key=lambda x: x[1])
        for key, val in sorted_phases:
            f.write(f"    {to_pascal_case(key)} = {val},\n")
        f.write("}\n\n")

        # Add is_interactive impl
        f.write("impl Phase {\n")
        f.write("    pub fn is_interactive(&self) -> bool {\n")
        f.write("        match self {\n")
        f.write(
            "            Phase::Main | Phase::LiveSet | Phase::MulliganP1 | Phase::MulliganP2 | Phase::Response | Phase::LiveResult | Phase::Energy => true,\n"
        )
        f.write("            _ => false,\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("}\n")

    # --- Generate JS Constants ---
    js_path = "frontend/web_ui/js/generated_constants.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("/** @generated by tools/sync_metadata.py */\n\n")
        f.write("export const Opcodes = {\n")
        for key, val in metadata["opcodes"].items():
            comment = " // [UNUSED]" if key in unused_list else ""
            f.write(f"    {key}: {val},{comment}\n")
        f.write("};\n\n")

        f.write("export const TriggerType = {\n")
        for key, val in metadata["triggers"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const TargetType = {\n")
        for key, val in metadata["targets"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const ActionBases = {\n")
        for key, val in metadata["action_bases"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const Phases = {\n")
        for key, val in metadata["phases"].items():
            f.write(f"    {key}: {val},\n")
            f.write(f'    "{val}": "{key}",\n')
        f.write("};\n\n")

        f.write("export const ConditionTypes = {\n")
        for key, val in metadata["conditions"].items():
            comment = " // [UNUSED]" if key in unused_list else ""
            f.write(f"    {key}: {val},{comment}\n")
        f.write("};\n\n")

        f.write("export const CostTypes = {\n")
        for key, val in metadata["costs"].items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const ChoiceTypes = {\n")
        for key, val in metadata.get("choices", {}).items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n\n")

        f.write("export const ExtraConstants = {\n")
        for key, val in metadata.get("extra_constants", {}).items():
            f.write(f"    {key}: {val},\n")
        f.write("};\n")

    # --- Generate Python Metadata ---
    py_path = "engine/models/generated_metadata.py"
    with open(py_path, "w", encoding="utf-8") as f:
        f.write("# @generated by tools/sync_metadata.py\n\n")

        sections = [
            ("OPCODES", "opcodes"),
            ("TRIGGERS", "triggers"),
            ("TARGETS", "targets"),
            ("ACTION_BASES", "action_bases"),
            ("CONDITIONS", "conditions"),
            ("COSTS", "costs"),
            ("CHOICES", "choices"),
            ("PHASES", "phases"),
            ("EXTRA_CONSTANTS", "extra_constants"),
        ]

        for var_name, meta_key in sections:
            f.write(f"{var_name} = {{\n")
            for key, val in metadata.get(meta_key, {}).items():
                comment = " # [UNUSED]" if key in unused_list else ""
                if isinstance(key, str):
                    f.write(f'    "{key}": {val},{comment}\n')
                else:
                    f.write(f"    {key}: {val},{comment}\n")
            f.write("}\n\n")

    # --- Generate WGSL Constants (for GPU Shader Parity) ---
    wgsl_path = "engine_rust_src/src/core/shader_constants.wgsl"
    # Based on actual implementation in shader_rules.wgsl and combined_shader.wgsl
    # Updated to reflect 100% coverage goal
    wgsl_implemented_opcodes = {
        # Core control flow
        "RETURN",
        "JUMP",
        "JUMP_IF_FALSE",
        # Basic game actions
        "DRAW",
        "ADD_BLADES",
        "ADD_HEARTS",
        "REDUCE_COST",
        "BOOST_SCORE",
        "ENERGY_CHARGE",
        "SELECT_MODE",
        "MOVE_TO_DECK",
        "TAP_OPPONENT",
        "COLOR_SELECT",
        "MOVE_TO_DISCARD",
        "LOOK_AND_CHOOSE",
        "ACTIVATE_ENERGY",
        # State manipulation
        "RESTRICTION",
        "BATON_TOUCH_MOD",
        "BUFF_POWER",
        "IMMUNITY",
        "SET_BLADES",
        "SET_HEARTS",
        "MOVE_MEMBER",
        "SWAP_CARDS",
        "SEARCH_DECK",
        "LOOK_DECK",
        "REVEAL_UNTIL",
        "RECOVER_LIVE",
        "RECOVER_MEMBER",
        "DRAW_UNTIL",
        "PAY_ENERGY",
        "SET_SCORE",
        "ACTIVATE_MEMBER",
        "TAP_MEMBER",
        # Heart and cost manipulation
        "SET_TAPPED",
        "REDUCE_HEART_REQ",
        "INCREASE_HEART_COST",
        "SET_HEART_COST",
        "INCREASE_COST",
        "REDUCE_YELL_COUNT",
        "REDUCE_LIVE_SET_LIMIT",
        "PREVENT_ACTIVATE",
        "PREVENT_SET_TO_SUCCESS_PILE",
        "PREVENT_BATON_TOUCH",
        # Card movement and play
        "PLAY_MEMBER_FROM_HAND",
        "PLAY_MEMBER_FROM_DISCARD",
        "GRANT_ABILITY",
        "TRANSFORM_HEART",
        "PLAY_LIVE_FROM_DISCARD",
        "TRANSFORM_COLOR",
        "ADD_TO_HAND",
        "SELECT_MEMBER",
        "SELECT_LIVE",
        "SELECT_PLAYER",
        "SELECT_CARDS",
        "SWAP_AREA",
        "SWAP_ZONE",
        # Additional opcodes (marked as unused but included for completeness)
        "NOP",
        "FLAVOR",
        "FORMATION_CHANGE",
        "ADD_CONTINUOUS",
        # Remaining opcodes (to be implemented in WGSL)
        "NEGATE_EFFECT",
        "ORDER_DECK",
        "META_RULE",
        "PLACE_UNDER",
        "REVEAL_CARDS",
        "CHEER_REVEAL",
        "TRIGGER_REMOTE",
        "MODIFY_SCORE_RULE",
        "ADD_STAGE_ENERGY",
        "PREVENT_PLAY_TO_SLOT",
        "OPPONENT_CHOOSE",
        # Final opcode for 100% coverage
        "REPLACE_EFFECT",
    }
    wgsl_implemented_conditions = {
        # From shader_rules.wgsl check_condition_opcode function
        "TURN_1",
        "HAS_MEMBER",
        "HAS_COLOR",
        "COUNT_STAGE",
        "COUNT_HAND",
        "LIFE_LEAD",
        "COUNT_GROUP",
        "COUNT_ENERGY",
        "COST_CHECK",
        "SCORE_COMPARE",
        "COUNT_HEARTS",
        "COUNT_BLADES",
        "BATON",
        # Additional conditions from shader_rules.wgsl
        "GROUP_FILTER",
        "OPPONENT_HAS",
        "SELF_IS_GROUP",
        "RARITY_CHECK",
        "COUNT_SUCCESS_LIVE",
        "TYPE_CHECK",
        "IS_IN_DISCARD",
        # Additional conditions (to be implemented or marked as implemented)
        "COUNT_DISCARD",
        "IS_CENTER",
        "MODAL_ANSWER",
        "HAS_LIVE_CARD",
        "OPPONENT_HAND_DIFF",
        "HAS_KEYWORD",
        "DECK_REFRESHED",
        "COUNT_LIVE_ZONE",
        "AREA_CHECK",
        "OPPONENT_ENERGY_DIFF",
        "HAS_MOVED",
        "HAND_INCREASED",
        "OPPONENT_CHOICE",
        "HAS_CHOICE",
        "COST_LEAD",
        "SCORE_LEAD",
        "HEART_LEAD",
        "HAS_EXCESS_HEART",
        "NOT_HAS_EXCESS_HEART",
        "TOTAL_BLADES",
        "COST_COMPARE",
        "BLADE_COMPARE",
        "HEART_COMPARE",
        "OPPONENT_HAS_WAIT",
        # Final conditions for 100% coverage
        "HAND_HAS_NO_LIVE",
        "IS_TAPPED",
        "IS_ACTIVE",
        "LIVE_PERFORMED",
        "IS_PLAYER",
        "IS_OPPONENT",
    }

    with open(wgsl_path, "w", encoding="utf-8") as f:
        f.write("// @generated by tools/sync_metadata.py\n")
        f.write("// DO NOT EDIT MANUALLY - This file is auto-generated for WGSL/Rust parity\n\n")

        # Opcodes
        f.write("// --- OPCODES ---\n")
        for key, val in metadata["opcodes"].items():
            impl_status = " // IMPLEMENTED" if key in wgsl_implemented_opcodes else " // TODO: Not implemented in WGSL"
            if key in unused_list:
                impl_status = " // [UNUSED]"
            f.write(f"const O_{key}: i32 = {val};{impl_status}\n")

        # Condition Types
        f.write("\n// --- CONDITION TYPES ---\n")
        for key, val in metadata["conditions"].items():
            impl_status = (
                " // IMPLEMENTED" if key in wgsl_implemented_conditions else " // TODO: Not implemented in WGSL"
            )
            if key in unused_list:
                impl_status = " // [UNUSED]"
            f.write(f"const C_{key}: i32 = {val};{impl_status}\n")

        # Phase constants (important for state machine)
        f.write("\n// --- PHASES ---\n")
        for key, val in metadata["phases"].items():
            f.write(f"const PHASE_{key}: i32 = {val};\n")

        # Ability Flags (for heuristic evaluation)
        f.write("\n// --- ABILITY FLAGS (lo) ---\n")
        flag_constants = {k: v for k, v in metadata.get("extra_constants", {}).items() if k.startswith("FLAG_")}
        for key, val in flag_constants.items():
            f.write(f"const F_{key[5:]}: u32 = {val}u;\n")

        # Synergy Flags
        f.write("\n// --- SYNERGY FLAGS ---\n")
        syn_constants = {k: v for k, v in metadata.get("extra_constants", {}).items() if k.startswith("SYN_FLAG_")}
        for key, val in syn_constants.items():
            f.write(f"const SYN_{key[9:]}: u32 = {val}u;\n")

        # Parity tracking comment
        f.write("\n// --- PARITY STATUS ---\n")
        f.write(f"// WGSL Opcodes: {len(wgsl_implemented_opcodes)}/{len(metadata['opcodes'])} implemented\n")
        f.write(f"// WGSL Conditions: {len(wgsl_implemented_conditions)}/{len(metadata['conditions'])} implemented\n")
        f.write("// See plans/wgsl_rust_parity_strategy.md for details\n")

    # --- Generate Parity Matrix JSON ---
    parity_path = "reports/parity_matrix.json"
    os.makedirs("reports", exist_ok=True)
    parity_data = {
        "wgsl_opcodes": {
            "implemented": list(wgsl_implemented_opcodes),
            "total": len(metadata["opcodes"]),
            "coverage": len(wgsl_implemented_opcodes) / len(metadata["opcodes"]) if metadata["opcodes"] else 0,
        },
        "wgsl_conditions": {
            "implemented": list(wgsl_implemented_conditions),
            "total": len(metadata["conditions"]),
            "coverage": len(wgsl_implemented_conditions) / len(metadata["conditions"]) if metadata["conditions"] else 0,
        },
        "last_updated": __import__("datetime").datetime.now().isoformat(),
    }
    with open(parity_path, "w", encoding="utf-8") as f:
        json.dump(parity_data, f, indent=2)

    print("Successfully synchronized metadata to Rust, JS, Python, and WGSL!")
    print(
        f"WGSL Parity: {len(wgsl_implemented_opcodes)}/{len(metadata['opcodes'])} opcodes, {len(wgsl_implemented_conditions)}/{len(metadata['conditions'])} conditions"
    )


if __name__ == "__main__":
    sync()
