// @generated by tools/codegen_abilities.py on 2026-03-28T07:53:36.255954
// GENERATED CODE - DO NOT EDIT
use crate::core::logic::{GameState, CardDatabase, AbilityContext};

pub fn execute_hardcoded_ability(state: &mut GameState, _db: &CardDatabase, card_id: i32, ab_idx: usize, ctx: &AbilityContext) -> bool {
    let p_idx = ctx.player_id as usize;
    match (card_id, ab_idx) {
        _ => false,
    }
}