// @generated by tools/codegen_abilities.py on 2026-03-23T02:16:03.606117
// GENERATED CODE - DO NOT EDIT
use crate::core::logic::{GameState, CardDatabase, AbilityContext};

pub fn execute_hardcoded_ability(state: &mut GameState, _db: &CardDatabase, card_id: i32, ab_idx: usize, ctx: &AbilityContext) -> bool {
    let p_idx = ctx.player_id as usize;
    match (card_id, ab_idx) {
        (13, 0) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            true
        },
        (14, 0) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            true
        },
        (644, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (55, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            true
        },
        (4151, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            true
        },
        (8247, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            true
        },
        (12343, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            true
        },
        (58, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4154, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (59, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4155, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (61, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4157, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (71, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (652, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (4748, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (8844, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (12940, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (657, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 2 as i32);
            true
        },
        (4753, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 2 as i32);
            true
        },
        (8849, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 2 as i32);
            true
        },
        (675, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            true
        },
        (4771, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            true
        },
        (89, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (89, 2) => {
            state.players[p_idx].live_score_bonus += 2;
            true
        },
        (4185, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4185, 2) => {
            state.players[p_idx].live_score_bonus += 2;
            true
        },
        (97, 0) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            true
        },
        (4193, 0) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            true
        },
        (98, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4194, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (99, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (4195, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (100, 2) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (4196, 2) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (166, 0) => {
            state.activate_energy(p_idx, 2);
            true
        },
        (4262, 0) => {
            state.activate_energy(p_idx, 2);
            true
        },
        (168, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4264, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (8360, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (12456, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (170, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (4266, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (172, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (4268, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (189, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (4285, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (8381, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (12477, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (694, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (4790, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (8886, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (12982, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (696, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 0;
            true
        },
        (4792, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 0;
            true
        },
        (8888, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 0;
            true
        },
        (699, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4795, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (8891, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (702, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (704, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (705, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (707, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 1 as i32);
            true
        },
        (720, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(4 as usize, 1 as i32);
            true
        },
        (721, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (739, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (239, 1) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (4335, 1) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (8431, 1) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (12527, 1) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (245, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4341, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (8437, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (12533, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (274, 0) => {
            true
        },
        (4370, 0) => {
            true
        },
        (277, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4373, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (8469, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (12565, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (303, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 2 as i32);
            true
        },
        (4399, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 2 as i32);
            true
        },
        (8495, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 2 as i32);
            true
        },
        (12591, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 2 as i32);
            true
        },
        (308, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4404, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (752, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4848, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (8944, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (756, 0) => {
            true
        },
        (4852, 0) => {
            true
        },
        (8948, 0) => {
            true
        },
        (762, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(1 as usize, 1 as i32);
            true
        },
        (4858, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(1 as usize, 1 as i32);
            true
        },
        (8954, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(1 as usize, 1 as i32);
            true
        },
        (13050, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(1 as usize, 1 as i32);
            true
        },
        (764, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (330, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4426, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (331, 0) => {
            state.draw_energy_cards(p_idx, 2);
            true
        },
        (331, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4427, 0) => {
            state.draw_energy_cards(p_idx, 2);
            true
        },
        (4427, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (333, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4429, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (335, 0) => {
            state.activate_energy(p_idx, 1);
            true
        },
        (4431, 0) => {
            state.activate_energy(p_idx, 1);
            true
        },
        (336, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 1 as i32);
            true
        },
        (4432, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 1 as i32);
            true
        },
        (337, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (4433, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (786, 0) => {
            state.activate_energy(p_idx, 2);
            true
        },
        (376, 0) => {
            state.activate_energy(p_idx, 2);
            true
        },
        (377, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (399, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (401, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (402, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (410, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (411, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (412, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (792, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 1 as i32);
            state.players[p_idx].blade_buffs[4 as usize] += 1;
            true
        },
        (793, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (415, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (4511, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (439, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4535, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (8631, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (12727, 1) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (441, 0) => {
            state.draw_cards(p_idx, 3 as u32);
            true
        },
        (4537, 0) => {
            state.draw_cards(p_idx, 3 as u32);
            true
        },
        (8633, 0) => {
            state.draw_cards(p_idx, 3 as u32);
            true
        },
        (12729, 0) => {
            state.draw_cards(p_idx, 3 as u32);
            true
        },
        (796, 1) => {
            state.players[p_idx].cost_reduction += 1;
            true
        },
        (4892, 1) => {
            state.players[p_idx].cost_reduction += 1;
            true
        },
        (8988, 1) => {
            state.players[p_idx].cost_reduction += 1;
            true
        },
        (13084, 1) => {
            state.players[p_idx].cost_reduction += 1;
            true
        },
        (803, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4899, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (8995, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (809, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (810, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (464, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (4560, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (468, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (4564, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (827, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 1 as i32);
            true
        },
        (839, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (840, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (847, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (496, 0) => {
            true
        },
        (4592, 0) => {
            true
        },
        (498, 0) => {
            true
        },
        (4594, 0) => {
            true
        },
        (8690, 0) => {
            true
        },
        (12786, 0) => {
            true
        },
        (499, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 5;
            true
        },
        (4595, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 5;
            true
        },
        (530, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (4626, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (559, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4655, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (561, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (4657, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (8753, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (12849, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (565, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (4661, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 3;
            true
        },
        (571, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 1 as i32);
            true
        },
        (576, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 1 as i32);
            true
        },
        (854, 2) => {
            state.activate_energy(p_idx, 1);
            true
        },
        (4950, 2) => {
            state.activate_energy(p_idx, 1);
            true
        },
        (9046, 2) => {
            state.activate_energy(p_idx, 1);
            true
        },
        (13142, 2) => {
            state.activate_energy(p_idx, 1);
            true
        },
        (856, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (856, 1) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            state.activate_energy(p_idx, 99);
            true
        },
        (4952, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (4952, 1) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            state.activate_energy(p_idx, 99);
            true
        },
        (9048, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (9048, 1) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            state.activate_energy(p_idx, 99);
            true
        },
        (13144, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (13144, 1) => {
            state.set_member_tapped(p_idx, 4 as usize, false);
            state.activate_energy(p_idx, 99);
            true
        },
        (864, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 3 as i32);
            true
        },
        (864, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 3 as i32);
            true
        },
        (864, 2) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 3 as i32);
            true
        },
        (4960, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 3 as i32);
            true
        },
        (4960, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 3 as i32);
            true
        },
        (4960, 2) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 3 as i32);
            true
        },
        (9056, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(2 as usize, 3 as i32);
            true
        },
        (9056, 1) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 3 as i32);
            true
        },
        (9056, 2) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(5 as usize, 3 as i32);
            true
        },
        (865, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(3 as usize, 1 as i32);
            true
        },
        (868, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (869, 0) => {
            state.players[p_idx].heart_buffs[4 as usize].add_to_color(6 as usize, 2 as i32);
            true
        },
        (870, 0) => {
            state.players[p_idx].cost_reduction += 2;
            true
        },
        (873, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (881, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4977, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (882, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4978, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (589, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (4685, 0) => {
            state.players[p_idx].live_score_bonus += 1;
            true
        },
        (593, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (593, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4689, 0) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (4689, 1) => {
            state.players[p_idx].blade_buffs[4 as usize] += 2;
            true
        },
        (594, 0) => {
            state.activate_energy(p_idx, 2);
            true
        },
        (4690, 0) => {
            state.activate_energy(p_idx, 2);
            true
        },
        (603, 0) => {
            state.draw_cards(p_idx, 1 as u32);
            true
        },
        (626, 0) => {
            state.draw_energy_cards(p_idx, 1);
            true
        },
        _ => false,
    }
}