import json
import re

# Keys explicitly present in ability_translator.js
SUPPORTED_KEYS = {
    # EffectType Opcodes
    "DRAW",
    "ADD_BLADES",
    "ADD_HEARTS",
    "REDUCE_COST",
    "LOOK_DECK",
    "RECOVER_LIVE",
    "BOOST_SCORE",
    "RECOVER_MEMBER",
    "BUFF_POWER",
    "IMMUNITY",
    "MOVE_MEMBER",
    "SWAP_CARDS",
    "SEARCH_DECK",
    "ENERGY_CHARGE",
    "ACTIVATE_MEMBER",
    "ADD_TO_HAND",
    "MOVE_TO_DECK",
    "REVEAL_CARDS",
    "LOOK_AND_CHOOSE",
    "TAP_OPPONENT",
    "TAP_MEMBER",
    "PLAY_MEMBER_FROM_HAND",
    "SET_BLADES",
    "SET_HEARTS",
    "FORMATION_CHANGE",
    "NEGATE_EFFECT",
    "ORDER_DECK",
    "BATON_TOUCH_MOD",
    "SET_SCORE",
    "SWAP_ZONE",
    "TRANSFORM_COLOR",
    "TRIGGER_REMOTE",
    "REDUCE_HEART_REQ",
    "COLOR_SELECT",
    "REPLACE_EFFECT",
    "MODIFY_SCORE_RULE",
    "MOVE_TO_DISCARD",
    "GRANT_ABILITY",
    "INCREASE_HEART_COST",
    "REDUCE_YELL_COUNT",
    "PLAY_MEMBER_FROM_DISCARD",
    "PAY_ENERGY",
    "SELECT_MEMBER",
    "DRAW_UNTIL",
    "SELECT_PLAYER",
    "SELECT_LIVE",
    "REVEAL_UNTIL",
    "INCREASE_COST",
    "PREVENT_PLAY_TO_SLOT",
    "SWAP_AREA",
    "TRANSFORM_HEART",
    "SELECT_CARDS",
    "OPPONENT_CHOOSE",
    "PLAY_LIVE_FROM_DISCARD",
    "REDUCE_LIVE_SET_LIMIT",
    "PREVENT_ACTIVATE",
    "FLAVOR_ACTION",
    "META_RULE",
    # String Keys & Newly Added
    "DISCARD_HAND",
    "ENERGY",
    "TAP_SELF",
    "SELECT_MODE",
    "CARD_DISCARD",
    "SELF",
    "PLAYER",
    "OPPONENT",
    "ENEMY",
    "MEMBER_NAMED",
    "ALL_MEMBERS",
    "ENEMY_STAGE",
    "HAS_KEYWORD",
    "HAS_MOVED",
    "COUNT_SUCCESS_LIVE",
    "HAS_LIVE_CARD",
    "TAP_PLAYER",
    "CARD_HAND",
    "TURN_1",
    "COUNT_STAGE",
    "OPTION",
    "ACTIVATE_ENERGY",
    "SUCCESS",
    "AREA",
    "TARGET_MEMBER",
    "IS_CENTER",
    "HAS_MEMBER",
    "HAS_COLOR",
    "COUNT_HAND",
    "COUNT_DISCARD",
    "LIFE_LEAD",
    "COUNT_GROUP",
    "GROUP_FILTER",
    "OPPONENT_HAS",
    "SELF_IS_GROUP",
    "MODAL_ANSWER",
    "COUNT_ENERGY",
    "COST_CHECK",
    "RARITY_CHECK",
    "HAND_HAS_NO_LIVE",
    "OPPONENT_HAND_DIFF",
    "SCORE_COMPARE",
    "HAS_CHOICE",
    "OPPONENT_CHOICE",
    "COUNT_HEARTS",
    "COUNT_BLADES",
    "OPPONENT_ENERGY_DIFF",
    "DECK_REFRESHED",
    "HAND_INCREASED",
    "COUNT_LIVE_ZONE",
    "BATON",
    "TYPE_CHECK",
    "COUNT_THIS_TURN",
    "BATON_TOUCH",
    "CHARGE_ENERGY",
    "TARGET_AREA",
    "POSITION_CHANGE",
    "TARGET_PLAYER",
    "REVEAL_HAND",
    "TYPE_MEMBER",
    "SUCCESS_LIVE",
    "BATON_FROM_NAME",
    "ACTIVATE_AND_SELF",
    "ADD_HEART",
    "ADD_TAG",
    "ALL",
    "ALL_AREAS",
    "ALL_ENERGY_ACTIVE",
    "ALL_MEMBER",
    "ANY_NOT_TARGETED_THIS_TURN",
    "AREA_IN",
    "BASE_BLADES_LE",
    "BATON_COUNT",
    "BATON_PASS",
    "BATON_REPLACED",
    "BATON_TOUCHED",
    "BLADE_GE_5",
    "BLADE_GE_9",
    "BLADE_LE_1",
    "BLADE_LE_3",
    "BOTH",
    "BOTH_PLAYERS",
    "CENTER",
    "CERISE",
    "CHANGE_BASE_HEART",
    "CHANGE_YELL_BLADE_COLOR",
    "CHARGED_ENERGY",
    "COLOR_BLUE",
    "COLOR_GREEN",
    "COLOR_PINK",
    "COLOR_PURPLE",
    "COLOR_RED",
    "COLOR_YELLOW",
    "CONSTANT",
    "COST_EQUAL_TARGET_PLUS_2",
    "COST_GE",
    "COST_GE_10",
    "COST_GE_13",
    "COST_GT",
    "COST_GT_SELF",
    "COST_LE",
    "COST_LEAD",
    "COST_LE_13",
    "COST_LE_2",
    "COST_LE_4",
    "COST_LE_9",
    "COST_LE_REVEALED",
    "COST_LT_DISCARDED",
    "COST_LT_SELF",
    "COUNT",
    "COUNT_ACTIVATED",
    "COUNT_CHARGED_ENERGY",
    "COUNT_DISCARDED_THIS_TURN",
    "COUNT_LIVE",
    "COUNT_MEMBER",
    "COUNT_PLAYED_THIS_TURN",
    "COUNT_UNIQUE_NAMES",
    "COUNT_YELL_REVEALED",
    "CYCLE",
    "DECK_BOTTOM",
    "DECK_REFRESHED_THIS_TURN",
    "DECK_TOP",
    "DISCARD",
    "DISCARDED",
    "DISCARDED_COST",
    "DISCARDED_THESE",
    "DISCARDED_THIS",
    "DISCARD_ENERGY",
    "DISCARD_HEART",
    "DISCARD_STAGE",
    "DIVE",
    "DOLLCHESTRA",
    "EFFECT_NEGATED_THIS_TURN",
    "EMOTION",
    "ENERGY_DECK",
    "ENERGY_LAGGING",
    "ENERGY_LEAD",
    "ENERGY_REMOVED",
    "EQUALS",
    "EXTRA_HEARTS",
    "FILTER",
    "FROM",
    "FROM_DISCARD",
    "GREATER_THAN",
    "GROUP",
    "GROUP_ID",
    "HAND",
    "HAND_OTHER",
    "HAND_SIZE",
    "HAND_SIZE_DIFF",
    "HAS_ACTIVE_ENERGY",
    "HAS_ALL_BLADE",
    "HAS_ALL_COLORS",
    "HAS_BLADE_HEART",
    "HAS_EXCESS_HEART",
    "HAS_HEART_TYPE",
    "HAS_LIVE_HEART_COLORS",
    "HAS_MOVED_THIS_TURN",
    "HAS_REMAINING_HEART",
    "HAS_SUCCESS_LIVE",
    "HAS_TYPE_LIVE",
    "HEART_COLORS",
    "HEART_GE_3",
    "HEART_LEAD",
    "HEART_MIN",
    "HEART_TYPE",
    "HIGHEST_COST_ON_STAGE",
    "INCREASE_HEART",
    "IS_IN_DISCARD",
    "IS_IN_HAND",
    "IS_ON_STAGE",
    "KALEIDOSCORE",
    "LEFT",
    "LEFT_SIDE",
    "LESS_THAN",
    "LIST",
    "LIVE",
    "LIVE_AREA",
    "LIVE_END",
    "LIVE_IN_PROGRESS",
    "LOOK_AND_CHOOSE_ORDER",
    "LOOK_AND_CHOOSE_REVEALED",
    "MAIN_PHASE",
    "MATCH_BASE_BLADE",
    "MATCH_COST",
    "MATCH_HEART",
    "MAX",
    "MEMBER",
    "MEMBER_AT_SLOT",
    "MIN",
    "MIRAKURA",
    "MODE",
    "NAME",
    "NAME_IN",
    "NEXT_TURN",
    "NONE",
    "NON_CENTER",
    "NOT_HAS_BLADE_HEART",
    "NOT_MOVED_THIS_TURN",
    "NOT_NAME",
    "NOT_TARGET",
    "NO_ABILITY",
    "ON_LIVE_START",
    "ON_LIVE_SUCCESS",
    "ON_PLAY",
    "OPPONENT_HAS_WAIT",
    "OPPONENT_LIVE",
    "OPPONENT_SCORE_ZERO_THIS_TURN",
    "OPPONENT_STAGE",
    "OPPONENT_WAIT",
    "OTHER",
    "OTHER_MEMBER",
    "OTHER_UNIT_MIRAKURA",
    "PER_CARD",
    "PER_ENERGY",
    "PER_ENERGY_PAID",
    "PER_HAND",
    "PLAYED",
    "PLAY_LIVE_FROM_HAND",
    "PREVENT_LIVE",
    "PREVENT_SET_TO_SUCCESS_PILE",
    "PRINTEMPS",
    "RECOVERED_THIS",
    "REDUCE_HEART",
    "REDUCE_PER",
    "REMOVE_ENERGY_FROM_MEMBER",
    "REPLACE_DISCARDED",
    "RESET_YELL_HEARTS",
    "REVEALED_LIVE",
    "REVEALED_OPTIONS",
    "REVEALED_THIS",
    "REVERSED",
    "RIGHT",
    "RIGHT_SIDE",
    "SAME_AS_TARGET",
    "SAME_NAME_MEMBER",
    "SAME_SLOT",
    "SCORE",
    "SCORE_GE",
    "SCORE_LE",
    "SCORE_LEAD",
    "SCORE_LE_3",
    "SCORE_TOTAL",
    "SELECTED",
    "SET_BASE_BLADES",
    "SLOT",
    "STAGE",
    "STAGE_ENTRY",
    "SUB_GROUP",
    "SUCCESS_PILE",
    "SUM_COST",
    "SUM_COST_IN",
    "SUM_ENERGY",
    "SUM_HEARTS",
    "SUM_SCORE",
    "SUM_SUCCESS_LIVE",
    "TAPPED",
    "TARGET",
    "TARGET_1",
    "TARGET_2",
    "TARGET_CARD",
    "TARGET_FILTER",
    "TARGET_LIVE",
    "TIE_BREAKER",
    "TONIGHT",
    "TRIGGER",
    "TRIGGER_YELL_AGAIN",
    "TRUE",
    "TYPE",
    "TYPE_LIVE",
    "UNIQUE_HEART_COLORS",
    "UNIQUE_NAMES",
    "UNIT",
    "UNIT_BIBI",
    "UNIT_CERISE",
    "UNIT_DOLL",
    "UNIT_HASU",
    "UNIT_LILYWHITE",
    "UNIT_MIRAKURA",
    "UNIT_PRINTEMPS",
    "UNTIL",
    "WAIT",
    "YELL_COUNT",
    "YELL_REVEALED",
    "ZONE",
}


def analyze_text_coverage():
    try:
        path = "engine/data/cards_compiled.json"
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: {path} not found.")
        return

    cards = []
    if "member_db" in data:
        cards.extend(data["member_db"].values())
    if "live_db" in data:
        cards.extend(data["live_db"].values())

    total_cards = len(cards)
    cards_with_text = 0
    fully_covered = 0
    partially_covered = 0
    unsupported_keys = {}

    for card in cards:
        raw_text = None
        if "abilities" in card and card["abilities"]:
            texts = [ab["raw_text"] for ab in card["abilities"] if "raw_text" in ab]
            if texts:
                raw_text = "\n".join(texts)
        if not raw_text:
            raw_text = card.get("ability_text") or card.get("pseudocode")
        if not raw_text:
            continue

        cards_with_text += 1
        lines = raw_text.split("\n")
        all_lines_ok = True

        for line in lines:
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            if line.startswith("TRIGGER:"):
                continue

            # Simplified matching to align with find_missing_keys.py
            found = re.findall(r"([A-Z][A-Z0-9_]{2,})", line)
            for opcode in found:
                if opcode in ["EFFECT", "COST", "CONDITION", "PLAYER", "OPPONENT", "SELF"]:
                    continue
                if opcode not in SUPPORTED_KEYS:
                    all_lines_ok = False
                    unsupported_keys[opcode] = unsupported_keys.get(opcode, 0) + 1

        if all_lines_ok:
            fully_covered += 1
        else:
            partially_covered += 1

    print(f"Cards with Raw Text: {cards_with_text}")
    print(f"Fully Covered by Friendly Text: {fully_covered} ({fully_covered / cards_with_text * 100:.1f}%)")
    print(f"Partially Covered: {partially_covered}")

    print("\nMost Common Unsupported Keys:")
    sorted_unsupported = sorted(unsupported_keys.items(), key=lambda x: x[1], reverse=True)
    for op, count in sorted_unsupported[:10]:
        print(f"Key '{op}': {count} cards")


if __name__ == "__main__":
    analyze_text_coverage()
